# Form implementation generated from reading ui file 'src\qus\seg_loading\ui\frame_selection.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_constructRoi(object):
    def setupUi(self, constructRoi):
        constructRoi.setObjectName("constructRoi")
        constructRoi.setMinimumSize(QtCore.QSize(1400, 662))
        constructRoi.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.main_layout = QtWidgets.QVBoxLayout(constructRoi)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=constructRoi)
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.full_screen_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.full_screen_layout.setObjectName("full_screen_layout")
        self.side_bar_layout = QtWidgets.QVBoxLayout()
        self.side_bar_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.side_bar_layout.setSpacing(0)
        self.side_bar_layout.setObjectName("side_bar_layout")
        self.sidebar = QtWidgets.QWidget(parent=self.horizontalLayoutWidget_4)
        self.sidebar.setMinimumSize(QtCore.QSize(341, 601))
        self.sidebar.setMaximumSize(QtCore.QSize(241, 601))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.imageSelectionSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.imageSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.imageSelectionSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.imageSelectionSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.imageSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.imageSelectionSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.imageSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.imageSelectionSidebar.setObjectName("imageSelectionSidebar")
        self.imageSelectionLabelSidebar = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.imageSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.imageSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageSelectionLabelSidebar.setObjectName("imageSelectionLabelSidebar")
        self.imageLabel = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.imageLabel.setGeometry(QtCore.QRect(-60, 40, 191, 51))
        self.imageLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.phantomLabel = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.phantomLabel.setGeometry(QtCore.QRect(-50, 70, 191, 51))
        self.phantomLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold\n"
"}")
        self.phantomLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.phantomLabel.setObjectName("phantomLabel")
        self.image_path_input = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.image_path_input.setGeometry(QtCore.QRect(100, 40, 241, 51))
        self.image_path_input.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.image_path_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.image_path_input.setObjectName("image_path_input")
        self.phantom_path_input = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.phantom_path_input.setGeometry(QtCore.QRect(100, 70, 241, 51))
        self.phantom_path_input.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.phantom_path_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.phantom_path_input.setObjectName("phantom_path_input")
        self.roiSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.roiSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.roiSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.roiSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.roiSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.roiSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.roiSidebar.setObjectName("roiSidebar")
        self.roiSidebarLabel = QtWidgets.QLabel(parent=self.roiSidebar)
        self.roiSidebarLabel.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.roiSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.roiSidebarLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.roiSidebarLabel.setObjectName("roiSidebarLabel")
        self.rfAnalysisSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.rfAnalysisSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.rfAnalysisSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.rfAnalysisSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.rfAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.rfAnalysisSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rfAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rfAnalysisSidebar.setObjectName("rfAnalysisSidebar")
        self.rfAnalysisLabel = QtWidgets.QLabel(parent=self.rfAnalysisSidebar)
        self.rfAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.rfAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.rfAnalysisLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rfAnalysisLabel.setObjectName("rfAnalysisLabel")
        self.exportResultsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.exportResultsSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.exportResultsSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.exportResultsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.exportResultsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.exportResultsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.exportResultsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.exportResultsSidebar.setObjectName("exportResultsSidebar")
        self.exportResultsLabel = QtWidgets.QLabel(parent=self.exportResultsSidebar)
        self.exportResultsLabel.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.exportResultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.exportResultsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exportResultsLabel.setObjectName("exportResultsLabel")
        self.analysisParamsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.analysisParamsSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisParamsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.analysisParamsSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisParamsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.analysisParamsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.analysisParamsSidebar.setObjectName("analysisParamsSidebar")
        self.analysisParamsLabel = QtWidgets.QLabel(parent=self.analysisParamsSidebar)
        self.analysisParamsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisParamsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisParamsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.analysisParamsLabel.setObjectName("analysisParamsLabel")
        self.side_bar_layout.addWidget(self.sidebar)
        self.gridFrame = QtWidgets.QFrame(parent=self.horizontalLayoutWidget_4)
        self.gridFrame.setMaximumSize(QtCore.QSize(341, 16777215))
        self.gridFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.gridFrame.setObjectName("gridFrame")
        self.backButtonGrid = QtWidgets.QGridLayout(self.gridFrame)
        self.backButtonGrid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.backButtonGrid.setContentsMargins(10, 10, 10, 10)
        self.backButtonGrid.setObjectName("backButtonGrid")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.backButtonGrid.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.backButtonGrid.addItem(spacerItem1, 1, 1, 1, 1)
        self.back_button = QtWidgets.QPushButton(parent=self.gridFrame)
        self.back_button.setMinimumSize(QtCore.QSize(131, 41))
        self.back_button.setMaximumSize(QtCore.QSize(131, 41))
        self.back_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.backButtonGrid.addWidget(self.back_button, 1, 0, 1, 1)
        self.side_bar_layout.addWidget(self.gridFrame)
        self.full_screen_layout.addLayout(self.side_bar_layout)
        self.frame_preview_layout = QtWidgets.QVBoxLayout()
        self.frame_preview_layout.setContentsMargins(30, 30, 30, 30)
        self.frame_preview_layout.setSpacing(10)
        self.frame_preview_layout.setObjectName("frame_preview_layout")
        self.select_frame_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.select_frame_label.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.select_frame_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.select_frame_label.setScaledContents(False)
        self.select_frame_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.select_frame_label.setWordWrap(True)
        self.select_frame_label.setObjectName("select_frame_label")
        self.frame_preview_layout.addWidget(self.select_frame_label)
        self.im_display_frame = QtWidgets.QFrame(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.im_display_frame.sizePolicy().hasHeightForWidth())
        self.im_display_frame.setSizePolicy(sizePolicy)
        self.im_display_frame.setMinimumSize(QtCore.QSize(501, 321))
        self.im_display_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.im_display_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.im_display_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.im_display_frame.setObjectName("im_display_frame")
        self.frame_preview_layout.addWidget(self.im_display_frame)
        self.frameControlsLayout = QtWidgets.QHBoxLayout()
        self.frameControlsLayout.setSpacing(10)
        self.frameControlsLayout.setObjectName("frameControlsLayout")
        self.frame_slider = QtWidgets.QSlider(parent=self.horizontalLayoutWidget_4)
        self.frame_slider.setMinimumSize(QtCore.QSize(251, 41))
        self.frame_slider.setMaximumSize(QtCore.QSize(251, 41))
        self.frame_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.frameControlsLayout.addWidget(self.frame_slider)
        self.cur_frame_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.cur_frame_label.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.cur_frame_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.cur_frame_label.setScaledContents(False)
        self.cur_frame_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.cur_frame_label.setWordWrap(True)
        self.cur_frame_label.setObjectName("cur_frame_label")
        self.frameControlsLayout.addWidget(self.cur_frame_label)
        self.of_frames_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.of_frames_label.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.of_frames_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.of_frames_label.setScaledContents(False)
        self.of_frames_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.of_frames_label.setWordWrap(True)
        self.of_frames_label.setObjectName("of_frames_label")
        self.frameControlsLayout.addWidget(self.of_frames_label)
        self.total_frames_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.total_frames_label.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.total_frames_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.total_frames_label.setScaledContents(False)
        self.total_frames_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.total_frames_label.setWordWrap(True)
        self.total_frames_label.setObjectName("total_frames_label")
        self.frameControlsLayout.addWidget(self.total_frames_label)
        self.accept_frame_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.accept_frame_button.setMinimumSize(QtCore.QSize(201, 41))
        self.accept_frame_button.setMaximumSize(QtCore.QSize(201, 41))
        self.accept_frame_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.accept_frame_button.setObjectName("accept_frame_button")
        self.frameControlsLayout.addWidget(self.accept_frame_button)
        self.frame_preview_layout.addLayout(self.frameControlsLayout)
        self.frame_preview_layout.setStretch(0, 1)
        self.frame_preview_layout.setStretch(2, 1)
        self.full_screen_layout.addLayout(self.frame_preview_layout)
        self.main_layout.addWidget(self.horizontalLayoutWidget_4)

        self.retranslateUi(constructRoi)
        QtCore.QMetaObject.connectSlotsByName(constructRoi)

    def retranslateUi(self, constructRoi):
        _translate = QtCore.QCoreApplication.translate
        constructRoi.setWindowTitle(_translate("constructRoi", "Select Region of Interest"))
        self.sidebar.setToolTip(_translate("constructRoi", "<html><head/><body><p><br/></p></body></html>"))
        self.imageSelectionLabelSidebar.setText(_translate("constructRoi", "Image Selection:"))
        self.imageLabel.setText(_translate("constructRoi", "Image:"))
        self.phantomLabel.setText(_translate("constructRoi", "Phantom:"))
        self.image_path_input.setText(_translate("constructRoi", "Sample filename "))
        self.phantom_path_input.setText(_translate("constructRoi", "Sample filename "))
        self.roiSidebarLabel.setText(_translate("constructRoi", "Segmentation Selection"))
        self.rfAnalysisLabel.setText(_translate("constructRoi", "Radio Frequency Data Analysis"))
        self.exportResultsLabel.setText(_translate("constructRoi", "Visualization / Export"))
        self.analysisParamsLabel.setText(_translate("constructRoi", "Analysis Parameter Selection"))
        self.back_button.setText(_translate("constructRoi", "Back"))
        self.select_frame_label.setText(_translate("constructRoi", "Select Frame to Segment:"))
        self.cur_frame_label.setText(_translate("constructRoi", "0"))
        self.of_frames_label.setText(_translate("constructRoi", "of"))
        self.total_frames_label.setText(_translate("constructRoi", "0"))
        self.accept_frame_button.setText(_translate("constructRoi", "Accept Frame"))
