# Form implementation generated from reading ui file 'D:\Omid\0_main\05.01.2026\5_QuantUS-OpenSource\QuantUS\src\qus\seg_loading\ui\roi_preview.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_constructRoi(object):
    def setupUi(self, constructRoi):
        constructRoi.setObjectName("constructRoi")
        constructRoi.resize(1400, 665)
        constructRoi.setMinimumSize(QtCore.QSize(1400, 662))
        constructRoi.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.main_layout = QtWidgets.QVBoxLayout(constructRoi)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.full_screen_layout = QtWidgets.QHBoxLayout()
        self.full_screen_layout.setObjectName("full_screen_layout")
        self.side_bar_layout = QtWidgets.QVBoxLayout()
        self.side_bar_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.side_bar_layout.setSpacing(0)
        self.side_bar_layout.setObjectName("side_bar_layout")
        self.sidebar = QtWidgets.QWidget(parent=constructRoi)
        self.sidebar.setMinimumSize(QtCore.QSize(341, 601))
        self.sidebar.setMaximumSize(QtCore.QSize(241, 601))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.imageSelectionSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.imageSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.imageSelectionSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.imageSelectionSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.imageSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.imageSelectionSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.imageSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.imageSelectionSidebar.setObjectName("imageSelectionSidebar")
        self.imageSelectionLabelSidebar = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.imageSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.imageSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageSelectionLabelSidebar.setObjectName("imageSelectionLabelSidebar")
        self.imageLabel = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.imageLabel.setGeometry(QtCore.QRect(-60, 40, 191, 51))
        self.imageLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.phantomLabel = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.phantomLabel.setGeometry(QtCore.QRect(-50, 70, 191, 51))
        self.phantomLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold\n"
"}")
        self.phantomLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.phantomLabel.setObjectName("phantomLabel")
        self.image_path_input = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.image_path_input.setGeometry(QtCore.QRect(100, 40, 241, 51))
        self.image_path_input.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.image_path_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.image_path_input.setObjectName("image_path_input")
        self.phantom_path_input = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.phantom_path_input.setGeometry(QtCore.QRect(100, 70, 241, 51))
        self.phantom_path_input.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.phantom_path_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.phantom_path_input.setObjectName("phantom_path_input")
        self.roiSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.roiSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.roiSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.roiSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.roiSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.roiSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.roiSidebar.setObjectName("roiSidebar")
        self.roiSidebarLabel = QtWidgets.QLabel(parent=self.roiSidebar)
        self.roiSidebarLabel.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.roiSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.roiSidebarLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.roiSidebarLabel.setObjectName("roiSidebarLabel")
        self.rfAnalysisSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.rfAnalysisSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.rfAnalysisSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.rfAnalysisSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.rfAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.rfAnalysisSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rfAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rfAnalysisSidebar.setObjectName("rfAnalysisSidebar")
        self.rfAnalysisLabel = QtWidgets.QLabel(parent=self.rfAnalysisSidebar)
        self.rfAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.rfAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.rfAnalysisLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rfAnalysisLabel.setObjectName("rfAnalysisLabel")
        self.exportResultsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.exportResultsSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.exportResultsSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.exportResultsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.exportResultsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.exportResultsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.exportResultsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.exportResultsSidebar.setObjectName("exportResultsSidebar")
        self.exportResultsLabel = QtWidgets.QLabel(parent=self.exportResultsSidebar)
        self.exportResultsLabel.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.exportResultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.exportResultsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exportResultsLabel.setObjectName("exportResultsLabel")
        self.analysisParamsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.analysisParamsSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisParamsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.analysisParamsSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisParamsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.analysisParamsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.analysisParamsSidebar.setObjectName("analysisParamsSidebar")
        self.analysisParamsLabel = QtWidgets.QLabel(parent=self.analysisParamsSidebar)
        self.analysisParamsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisParamsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisParamsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.analysisParamsLabel.setObjectName("analysisParamsLabel")
        self.side_bar_layout.addWidget(self.sidebar)
        self.gridFrame = QtWidgets.QFrame(parent=constructRoi)
        self.gridFrame.setMaximumSize(QtCore.QSize(341, 16777215))
        self.gridFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.gridFrame.setObjectName("gridFrame")
        self.backButtonGrid = QtWidgets.QGridLayout(self.gridFrame)
        self.backButtonGrid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.backButtonGrid.setContentsMargins(10, 10, 10, 10)
        self.backButtonGrid.setObjectName("backButtonGrid")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.backButtonGrid.addItem(spacerItem, 0, 0, 1, 1)
        self.side_bar_layout.addWidget(self.gridFrame)
        self.full_screen_layout.addLayout(self.side_bar_layout)
        self.confirmation_layout = QtWidgets.QVBoxLayout()
        self.confirmation_layout.setContentsMargins(30, 10, 30, 10)
        self.confirmation_layout.setSpacing(10)
        self.confirmation_layout.setObjectName("confirmation_layout")
        self.segmentation_confirmation_label = QtWidgets.QLabel(parent=constructRoi)
        self.segmentation_confirmation_label.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.segmentation_confirmation_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.segmentation_confirmation_label.setScaledContents(False)
        self.segmentation_confirmation_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.segmentation_confirmation_label.setWordWrap(True)
        self.segmentation_confirmation_label.setObjectName("segmentation_confirmation_label")
        self.confirmation_layout.addWidget(self.segmentation_confirmation_label)
        self.seg_confirmation_info = QtWidgets.QFrame(parent=constructRoi)
        self.seg_confirmation_info.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.seg_confirmation_info.setObjectName("seg_confirmation_info")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.seg_confirmation_info)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.segmentation_name_label = QtWidgets.QLabel(parent=self.seg_confirmation_info)
        self.segmentation_name_label.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.segmentation_name_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.segmentation_name_label.setScaledContents(False)
        self.segmentation_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.segmentation_name_label.setWordWrap(False)
        self.segmentation_name_label.setObjectName("segmentation_name_label")
        self.horizontalLayout_7.addWidget(self.segmentation_name_label, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.segmentation_name_val = QtWidgets.QLabel(parent=self.seg_confirmation_info)
        self.segmentation_name_val.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.segmentation_name_val.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.segmentation_name_val.setScaledContents(False)
        self.segmentation_name_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.segmentation_name_val.setWordWrap(True)
        self.segmentation_name_val.setObjectName("segmentation_name_val")
        self.horizontalLayout_7.addWidget(self.segmentation_name_val, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.confirmation_layout.addWidget(self.seg_confirmation_info, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.seg_options_buttons = QtWidgets.QFrame(parent=constructRoi)
        self.seg_options_buttons.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.seg_options_buttons.setObjectName("seg_options_buttons")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.seg_options_buttons)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.confirm_seg_button = QtWidgets.QPushButton(parent=self.seg_options_buttons)
        self.confirm_seg_button.setMinimumSize(QtCore.QSize(221, 41))
        self.confirm_seg_button.setMaximumSize(QtCore.QSize(221, 41))
        self.confirm_seg_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.confirm_seg_button.setCheckable(True)
        self.confirm_seg_button.setChecked(False)
        self.confirm_seg_button.setObjectName("confirm_seg_button")
        self.horizontalLayout_10.addWidget(self.confirm_seg_button, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.back_from_confirm_button = QtWidgets.QPushButton(parent=self.seg_options_buttons)
        self.back_from_confirm_button.setMinimumSize(QtCore.QSize(241, 41))
        self.back_from_confirm_button.setMaximumSize(QtCore.QSize(241, 41))
        self.back_from_confirm_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 16px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.back_from_confirm_button.setCheckable(False)
        self.back_from_confirm_button.setChecked(False)
        self.back_from_confirm_button.setObjectName("back_from_confirm_button")
        self.horizontalLayout_10.addWidget(self.back_from_confirm_button, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.confirmation_layout.addWidget(self.seg_options_buttons)
        self.im_display_frame = QtWidgets.QFrame(parent=constructRoi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.im_display_frame.sizePolicy().hasHeightForWidth())
        self.im_display_frame.setSizePolicy(sizePolicy)
        self.im_display_frame.setMinimumSize(QtCore.QSize(501, 321))
        self.im_display_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.im_display_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.im_display_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.im_display_frame.setObjectName("im_display_frame")
        self.confirmation_layout.addWidget(self.im_display_frame)
        self.confirmation_frame_label = QtWidgets.QLabel(parent=constructRoi)
        self.confirmation_frame_label.setMinimumSize(QtCore.QSize(200, 0))
        self.confirmation_frame_label.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.confirmation_frame_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.confirmation_frame_label.setScaledContents(False)
        self.confirmation_frame_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.confirmation_frame_label.setWordWrap(True)
        self.confirmation_frame_label.setObjectName("confirmation_frame_label")
        self.confirmation_layout.addWidget(self.confirmation_frame_label, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.confirmation_layout.setStretch(0, 1)
        self.confirmation_layout.setStretch(1, 1)
        self.full_screen_layout.addLayout(self.confirmation_layout)
        self.main_layout.addLayout(self.full_screen_layout)

        self.retranslateUi(constructRoi)
        QtCore.QMetaObject.connectSlotsByName(constructRoi)

    def retranslateUi(self, constructRoi):
        _translate = QtCore.QCoreApplication.translate
        constructRoi.setWindowTitle(_translate("constructRoi", "Select Region of Interest"))
        self.sidebar.setToolTip(_translate("constructRoi", "<html><head/><body><p><br/></p></body></html>"))
        self.imageSelectionLabelSidebar.setText(_translate("constructRoi", "Image Selection:"))
        self.imageLabel.setText(_translate("constructRoi", "Image:"))
        self.phantomLabel.setText(_translate("constructRoi", "Phantom:"))
        self.image_path_input.setText(_translate("constructRoi", "Sample filename "))
        self.phantom_path_input.setText(_translate("constructRoi", "Sample filename "))
        self.roiSidebarLabel.setText(_translate("constructRoi", "Segmentation Selection"))
        self.rfAnalysisLabel.setText(_translate("constructRoi", "QUS Analysis"))
        self.exportResultsLabel.setText(_translate("constructRoi", "Visualization / Export"))
        self.analysisParamsLabel.setText(_translate("constructRoi", "Analysis Parameter Selection"))
        self.segmentation_confirmation_label.setText(_translate("constructRoi", "Segmentation:"))
        self.segmentation_name_label.setText(_translate("constructRoi", "Segmentation Name: "))
        self.segmentation_name_val.setText(_translate("constructRoi", "NAME"))
        self.confirm_seg_button.setText(_translate("constructRoi", "Confirm"))
        self.back_from_confirm_button.setText(_translate("constructRoi", "Back"))
        self.confirmation_frame_label.setText(_translate("constructRoi", "Frame: 0"))
