# Form implementation generated from reading ui file 'D:\Omid\0_main\05.01.2026\5_QuantUS-OpenSource\QuantUS\src\qus\seg_loading\ui\roi_drawing.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_constructRoi(object):
    def setupUi(self, constructRoi):
        constructRoi.setObjectName("constructRoi")
        constructRoi.resize(1400, 749)
        constructRoi.setMinimumSize(QtCore.QSize(1400, 662))
        constructRoi.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.main_layout = QtWidgets.QVBoxLayout(constructRoi)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.full_screen_layout = QtWidgets.QHBoxLayout()
        self.full_screen_layout.setObjectName("full_screen_layout")
        self.side_bar_layout = QtWidgets.QVBoxLayout()
        self.side_bar_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.side_bar_layout.setSpacing(0)
        self.side_bar_layout.setObjectName("side_bar_layout")
        self.sidebar = QtWidgets.QWidget(parent=constructRoi)
        self.sidebar.setMinimumSize(QtCore.QSize(341, 601))
        self.sidebar.setMaximumSize(QtCore.QSize(241, 601))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.imageSelectionSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.imageSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.imageSelectionSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.imageSelectionSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.imageSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.imageSelectionSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.imageSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.imageSelectionSidebar.setObjectName("imageSelectionSidebar")
        self.imageSelectionLabelSidebar = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.imageSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.imageSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageSelectionLabelSidebar.setObjectName("imageSelectionLabelSidebar")
        self.imageLabel = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.imageLabel.setGeometry(QtCore.QRect(-60, 40, 191, 51))
        self.imageLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.phantomLabel = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.phantomLabel.setGeometry(QtCore.QRect(-50, 70, 191, 51))
        self.phantomLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold\n"
"}")
        self.phantomLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.phantomLabel.setObjectName("phantomLabel")
        self.image_path_input = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.image_path_input.setGeometry(QtCore.QRect(100, 40, 241, 51))
        self.image_path_input.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.image_path_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.image_path_input.setObjectName("image_path_input")
        self.phantom_path_input = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.phantom_path_input.setGeometry(QtCore.QRect(100, 70, 241, 51))
        self.phantom_path_input.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.phantom_path_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.phantom_path_input.setObjectName("phantom_path_input")
        self.roiSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.roiSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.roiSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.roiSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.roiSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.roiSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.roiSidebar.setObjectName("roiSidebar")
        self.roiSidebarLabel = QtWidgets.QLabel(parent=self.roiSidebar)
        self.roiSidebarLabel.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.roiSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.roiSidebarLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.roiSidebarLabel.setObjectName("roiSidebarLabel")
        self.rfAnalysisSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.rfAnalysisSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.rfAnalysisSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.rfAnalysisSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.rfAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.rfAnalysisSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rfAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rfAnalysisSidebar.setObjectName("rfAnalysisSidebar")
        self.rfAnalysisLabel = QtWidgets.QLabel(parent=self.rfAnalysisSidebar)
        self.rfAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.rfAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.rfAnalysisLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rfAnalysisLabel.setObjectName("rfAnalysisLabel")
        self.exportResultsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.exportResultsSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.exportResultsSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.exportResultsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.exportResultsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.exportResultsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.exportResultsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.exportResultsSidebar.setObjectName("exportResultsSidebar")
        self.exportResultsLabel = QtWidgets.QLabel(parent=self.exportResultsSidebar)
        self.exportResultsLabel.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.exportResultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.exportResultsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exportResultsLabel.setObjectName("exportResultsLabel")
        self.analysisParamsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.analysisParamsSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisParamsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.analysisParamsSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisParamsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.analysisParamsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.analysisParamsSidebar.setObjectName("analysisParamsSidebar")
        self.analysisParamsLabel = QtWidgets.QLabel(parent=self.analysisParamsSidebar)
        self.analysisParamsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisParamsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisParamsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.analysisParamsLabel.setObjectName("analysisParamsLabel")
        self.side_bar_layout.addWidget(self.sidebar)
        self.gridFrame = QtWidgets.QFrame(parent=constructRoi)
        self.gridFrame.setMaximumSize(QtCore.QSize(341, 16777215))
        self.gridFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.gridFrame.setObjectName("gridFrame")
        self.backButtonGrid = QtWidgets.QGridLayout(self.gridFrame)
        self.backButtonGrid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.backButtonGrid.setContentsMargins(10, 10, 10, 10)
        self.backButtonGrid.setObjectName("backButtonGrid")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.backButtonGrid.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.backButtonGrid.addItem(spacerItem1, 1, 1, 1, 1)
        self.back_button = QtWidgets.QPushButton(parent=self.gridFrame)
        self.back_button.setMinimumSize(QtCore.QSize(131, 41))
        self.back_button.setMaximumSize(QtCore.QSize(131, 41))
        self.back_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.backButtonGrid.addWidget(self.back_button, 1, 0, 1, 1)
        self.side_bar_layout.addWidget(self.gridFrame)
        self.loading_screen_label = QtWidgets.QLabel(parent=constructRoi)
        self.loading_screen_label.setStyleSheet("QLabel {\n"
"    color: rgb(0, 255, 0);\n"
"    font-size: 20px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.loading_screen_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loading_screen_label.setObjectName("loading_screen_label")
        self.side_bar_layout.addWidget(self.loading_screen_label)
        self.full_screen_layout.addLayout(self.side_bar_layout)
        self.draw_roi_layout = QtWidgets.QVBoxLayout()
        self.draw_roi_layout.setContentsMargins(30, 10, 30, 10)
        self.draw_roi_layout.setSpacing(10)
        self.draw_roi_layout.setObjectName("draw_roi_layout")
        self.draw_roi_heading_layout = QtWidgets.QVBoxLayout()
        self.draw_roi_heading_layout.setSpacing(5)
        self.draw_roi_heading_layout.setObjectName("draw_roi_heading_layout")
        self.draw_roi_title_layout = QtWidgets.QHBoxLayout()
        self.draw_roi_title_layout.setObjectName("draw_roi_title_layout")
        self.pix_dim_layout_cm = QtWidgets.QVBoxLayout()
        self.pix_dim_layout_cm.setObjectName("pix_dim_layout_cm")
        self.physical_dims_label = QtWidgets.QLabel(parent=constructRoi)
        self.physical_dims_label.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.physical_dims_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.physical_dims_label.setScaledContents(False)
        self.physical_dims_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.physical_dims_label.setWordWrap(True)
        self.physical_dims_label.setObjectName("physical_dims_label")
        self.pix_dim_layout_cm.addWidget(self.physical_dims_label)
        self.pix_dim_grid_cm = QtWidgets.QGridLayout()
        self.pix_dim_grid_cm.setObjectName("pix_dim_grid_cm")
        self.physical_depth_label = QtWidgets.QLabel(parent=constructRoi)
        self.physical_depth_label.setMinimumSize(QtCore.QSize(129, 0))
        self.physical_depth_label.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.physical_depth_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.physical_depth_label.setScaledContents(False)
        self.physical_depth_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.physical_depth_label.setWordWrap(True)
        self.physical_depth_label.setObjectName("physical_depth_label")
        self.pix_dim_grid_cm.addWidget(self.physical_depth_label, 1, 0, 1, 1)
        self.physical_width_val = QtWidgets.QLabel(parent=constructRoi)
        self.physical_width_val.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.physical_width_val.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.physical_width_val.setScaledContents(False)
        self.physical_width_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.physical_width_val.setWordWrap(True)
        self.physical_width_val.setObjectName("physical_width_val")
        self.pix_dim_grid_cm.addWidget(self.physical_width_val, 0, 1, 1, 1)
        self.physical_depth_val = QtWidgets.QLabel(parent=constructRoi)
        self.physical_depth_val.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.physical_depth_val.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.physical_depth_val.setScaledContents(False)
        self.physical_depth_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.physical_depth_val.setWordWrap(True)
        self.physical_depth_val.setObjectName("physical_depth_val")
        self.pix_dim_grid_cm.addWidget(self.physical_depth_val, 1, 1, 1, 1)
        self.physical_width_label = QtWidgets.QLabel(parent=constructRoi)
        self.physical_width_label.setMinimumSize(QtCore.QSize(129, 0))
        self.physical_width_label.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.physical_width_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.physical_width_label.setScaledContents(False)
        self.physical_width_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.physical_width_label.setWordWrap(True)
        self.physical_width_label.setObjectName("physical_width_label")
        self.pix_dim_grid_cm.addWidget(self.physical_width_label, 0, 0, 1, 1)
        self.pix_dim_layout_cm.addLayout(self.pix_dim_grid_cm)
        self.pix_dim_layout_cm.setStretch(0, 1)
        self.pix_dim_layout_cm.setStretch(1, 2)
        self.draw_roi_title_layout.addLayout(self.pix_dim_layout_cm)
        self.construct_roi_label = QtWidgets.QLabel(parent=constructRoi)
        self.construct_roi_label.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.construct_roi_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.construct_roi_label.setScaledContents(False)
        self.construct_roi_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.construct_roi_label.setWordWrap(True)
        self.construct_roi_label.setObjectName("construct_roi_label")
        self.draw_roi_title_layout.addWidget(self.construct_roi_label)
        self.pix_dim_layout = QtWidgets.QVBoxLayout()
        self.pix_dim_layout.setObjectName("pix_dim_layout")
        self.pixel_dims_label = QtWidgets.QLabel(parent=constructRoi)
        self.pixel_dims_label.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.pixel_dims_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.pixel_dims_label.setScaledContents(False)
        self.pixel_dims_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pixel_dims_label.setWordWrap(True)
        self.pixel_dims_label.setObjectName("pixel_dims_label")
        self.pix_dim_layout.addWidget(self.pixel_dims_label)
        self.pix_dim_grid = QtWidgets.QGridLayout()
        self.pix_dim_grid.setObjectName("pix_dim_grid")
        self.pixel_width_label = QtWidgets.QLabel(parent=constructRoi)
        self.pixel_width_label.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.pixel_width_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.pixel_width_label.setScaledContents(False)
        self.pixel_width_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.pixel_width_label.setWordWrap(True)
        self.pixel_width_label.setObjectName("pixel_width_label")
        self.pix_dim_grid.addWidget(self.pixel_width_label, 0, 0, 1, 1)
        self.pixel_depth_label = QtWidgets.QLabel(parent=constructRoi)
        self.pixel_depth_label.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.pixel_depth_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.pixel_depth_label.setScaledContents(False)
        self.pixel_depth_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.pixel_depth_label.setWordWrap(True)
        self.pixel_depth_label.setObjectName("pixel_depth_label")
        self.pix_dim_grid.addWidget(self.pixel_depth_label, 1, 0, 1, 1)
        self.pixel_width_val = QtWidgets.QLabel(parent=constructRoi)
        self.pixel_width_val.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.pixel_width_val.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.pixel_width_val.setScaledContents(False)
        self.pixel_width_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.pixel_width_val.setWordWrap(True)
        self.pixel_width_val.setObjectName("pixel_width_val")
        self.pix_dim_grid.addWidget(self.pixel_width_val, 0, 1, 1, 1)
        self.pixel_depth_val = QtWidgets.QLabel(parent=constructRoi)
        self.pixel_depth_val.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.pixel_depth_val.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.pixel_depth_val.setScaledContents(False)
        self.pixel_depth_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.pixel_depth_val.setWordWrap(True)
        self.pixel_depth_val.setObjectName("pixel_depth_val")
        self.pix_dim_grid.addWidget(self.pixel_depth_val, 1, 1, 1, 1)
        self.pix_dim_layout.addLayout(self.pix_dim_grid)
        self.pix_dim_layout.setStretch(0, 1)
        self.pix_dim_layout.setStretch(1, 2)
        self.draw_roi_title_layout.addLayout(self.pix_dim_layout)
        self.draw_roi_title_layout.setStretch(0, 1)
        self.draw_roi_title_layout.setStretch(1, 2)
        self.draw_roi_title_layout.setStretch(2, 1)
        self.draw_roi_heading_layout.addLayout(self.draw_roi_title_layout)
        self.draw_roi_layout.addLayout(self.draw_roi_heading_layout)
        self.brightness_control_layout = QtWidgets.QHBoxLayout()
        self.brightness_control_layout.setSpacing(10)
        self.brightness_control_layout.setObjectName("brightness_control_layout")
        self.brightness_label = QtWidgets.QLabel(parent=constructRoi)
        self.brightness_label.setMinimumSize(QtCore.QSize(80, 41))
        self.brightness_label.setMaximumSize(QtCore.QSize(80, 41))
        self.brightness_label.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.brightness_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.brightness_label.setObjectName("brightness_label")
        self.brightness_control_layout.addWidget(self.brightness_label)
        self.brightness_slider = QtWidgets.QSlider(parent=constructRoi)
        self.brightness_slider.setMinimumSize(QtCore.QSize(200, 41))
        self.brightness_slider.setMaximumSize(QtCore.QSize(200, 41))
        self.brightness_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 8px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
"    margin: 2px 0;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 18px;\n"
"    margin: 2px 0;\n"
"    border-radius: 3px;\n"
"}")
        self.brightness_slider.setMinimum(0)
        self.brightness_slider.setMaximum(100)
        self.brightness_slider.setProperty("value", 0)
        self.brightness_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.brightness_slider.setObjectName("brightness_slider")
        self.brightness_control_layout.addWidget(self.brightness_slider)
        self.brightness_value_label = QtWidgets.QLabel(parent=constructRoi)
        self.brightness_value_label.setMinimumSize(QtCore.QSize(40, 41))
        self.brightness_value_label.setMaximumSize(QtCore.QSize(40, 41))
        self.brightness_value_label.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.brightness_value_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.brightness_value_label.setObjectName("brightness_value_label")
        self.brightness_control_layout.addWidget(self.brightness_value_label)
        self.draw_roi_layout.addLayout(self.brightness_control_layout)
        self.overlay_control_layout = QtWidgets.QHBoxLayout()
        self.overlay_control_layout.setSpacing(10)
        self.overlay_control_layout.setObjectName("overlay_control_layout")
        self.dicom_overlay_checkbox = QtWidgets.QCheckBox(parent=constructRoi)
        self.dicom_overlay_checkbox.setMinimumSize(QtCore.QSize(200, 41))
        self.dicom_overlay_checkbox.setMaximumSize(QtCore.QSize(200, 41))
        self.dicom_overlay_checkbox.setStyleSheet("QCheckBox {\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 15px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(90, 37, 255);\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(90, 37, 255);\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}")
        self.dicom_overlay_checkbox.setObjectName("dicom_overlay_checkbox")
        self.overlay_control_layout.addWidget(self.dicom_overlay_checkbox)
        self.transparency_label = QtWidgets.QLabel(parent=constructRoi)
        self.transparency_label.setMinimumSize(QtCore.QSize(100, 41))
        self.transparency_label.setMaximumSize(QtCore.QSize(100, 41))
        self.transparency_label.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.transparency_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.transparency_label.setObjectName("transparency_label")
        self.overlay_control_layout.addWidget(self.transparency_label)
        self.transparency_slider = QtWidgets.QSlider(parent=constructRoi)
        self.transparency_slider.setMinimumSize(QtCore.QSize(200, 41))
        self.transparency_slider.setMaximumSize(QtCore.QSize(200, 41))
        self.transparency_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 8px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
"    margin: 2px 0;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 18px;\n"
"    margin: 2px 0;\n"
"    border-radius: 3px;\n"
"}")
        self.transparency_slider.setMinimum(0)
        self.transparency_slider.setMaximum(100)
        self.transparency_slider.setProperty("value", 50)
        self.transparency_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.transparency_slider.setObjectName("transparency_slider")
        self.overlay_control_layout.addWidget(self.transparency_slider)
        self.transparency_value_label = QtWidgets.QLabel(parent=constructRoi)
        self.transparency_value_label.setMinimumSize(QtCore.QSize(40, 41))
        self.transparency_value_label.setMaximumSize(QtCore.QSize(40, 41))
        self.transparency_value_label.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.transparency_value_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.transparency_value_label.setObjectName("transparency_value_label")
        self.overlay_control_layout.addWidget(self.transparency_value_label)
        self.draw_roi_layout.addLayout(self.overlay_control_layout)
        self.load_dicom_button = QtWidgets.QPushButton(parent=constructRoi)
        self.load_dicom_button.setMinimumSize(QtCore.QSize(241, 41))
        self.load_dicom_button.setMaximumSize(QtCore.QSize(241, 41))
        self.load_dicom_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(120, 67, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(60, 17, 195);\n"
"}")
        self.load_dicom_button.setObjectName("load_dicom_button")
        self.draw_roi_layout.addWidget(self.load_dicom_button)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.back_from_drag_button = QtWidgets.QPushButton(parent=constructRoi)
        self.back_from_drag_button.setMinimumSize(QtCore.QSize(241, 41))
        self.back_from_drag_button.setMaximumSize(QtCore.QSize(241, 41))
        self.back_from_drag_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.back_from_drag_button.setCheckable(True)
        self.back_from_drag_button.setChecked(False)
        self.back_from_drag_button.setObjectName("back_from_drag_button")
        self.horizontalLayout_4.addWidget(self.back_from_drag_button)
        self.save_drag_button = QtWidgets.QPushButton(parent=constructRoi)
        self.save_drag_button.setMinimumSize(QtCore.QSize(241, 41))
        self.save_drag_button.setMaximumSize(QtCore.QSize(241, 41))
        self.save_drag_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.save_drag_button.setCheckable(True)
        self.save_drag_button.setChecked(False)
        self.save_drag_button.setObjectName("save_drag_button")
        self.horizontalLayout_4.addWidget(self.save_drag_button)
        self.draw_roi_layout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.draw_pts_type_button = QtWidgets.QPushButton(parent=constructRoi)
        self.draw_pts_type_button.setMinimumSize(QtCore.QSize(221, 41))
        self.draw_pts_type_button.setMaximumSize(QtCore.QSize(221, 41))
        self.draw_pts_type_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.draw_pts_type_button.setCheckable(True)
        self.draw_pts_type_button.setChecked(False)
        self.draw_pts_type_button.setObjectName("draw_pts_type_button")
        self.horizontalLayout.addWidget(self.draw_pts_type_button)
        self.draw_freehand_drag_type_button = QtWidgets.QPushButton(parent=constructRoi)
        self.draw_freehand_drag_type_button.setMinimumSize(QtCore.QSize(241, 41))
        self.draw_freehand_drag_type_button.setMaximumSize(QtCore.QSize(241, 41))
        self.draw_freehand_drag_type_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 16px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.draw_freehand_drag_type_button.setCheckable(False)
        self.draw_freehand_drag_type_button.setChecked(False)
        self.draw_freehand_drag_type_button.setObjectName("draw_freehand_drag_type_button")
        self.horizontalLayout.addWidget(self.draw_freehand_drag_type_button)
        self.draw_rect_drag_type_button = QtWidgets.QPushButton(parent=constructRoi)
        self.draw_rect_drag_type_button.setMinimumSize(QtCore.QSize(241, 41))
        self.draw_rect_drag_type_button.setMaximumSize(QtCore.QSize(241, 41))
        self.draw_rect_drag_type_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 16px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.draw_rect_drag_type_button.setCheckable(False)
        self.draw_rect_drag_type_button.setChecked(False)
        self.draw_rect_drag_type_button.setObjectName("draw_rect_drag_type_button")
        self.horizontalLayout.addWidget(self.draw_rect_drag_type_button)
        self.draw_roi_layout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clear_roi_button = QtWidgets.QPushButton(parent=constructRoi)
        self.clear_roi_button.setMinimumSize(QtCore.QSize(141, 41))
        self.clear_roi_button.setMaximumSize(QtCore.QSize(141, 41))
        self.clear_roi_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clear_roi_button.setCheckable(False)
        self.clear_roi_button.setObjectName("clear_roi_button")
        self.horizontalLayout_3.addWidget(self.clear_roi_button)
        self.undo_last_pt_button = QtWidgets.QPushButton(parent=constructRoi)
        self.undo_last_pt_button.setMinimumSize(QtCore.QSize(141, 41))
        self.undo_last_pt_button.setMaximumSize(QtCore.QSize(141, 41))
        self.undo_last_pt_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.undo_last_pt_button.setCheckable(False)
        self.undo_last_pt_button.setObjectName("undo_last_pt_button")
        self.horizontalLayout_3.addWidget(self.undo_last_pt_button)
        self.close_roi_button = QtWidgets.QPushButton(parent=constructRoi)
        self.close_roi_button.setMinimumSize(QtCore.QSize(141, 41))
        self.close_roi_button.setMaximumSize(QtCore.QSize(141, 41))
        self.close_roi_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.close_roi_button.setCheckable(False)
        self.close_roi_button.setObjectName("close_roi_button")
        self.horizontalLayout_3.addWidget(self.close_roi_button)
        self.back_from_pts_button = QtWidgets.QPushButton(parent=constructRoi)
        self.back_from_pts_button.setMinimumSize(QtCore.QSize(141, 41))
        self.back_from_pts_button.setMaximumSize(QtCore.QSize(141, 41))
        self.back_from_pts_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.back_from_pts_button.setCheckable(False)
        self.back_from_pts_button.setObjectName("back_from_pts_button")
        self.horizontalLayout_3.addWidget(self.back_from_pts_button)
        self.save_pts_button = QtWidgets.QPushButton(parent=constructRoi)
        self.save_pts_button.setMinimumSize(QtCore.QSize(141, 41))
        self.save_pts_button.setMaximumSize(QtCore.QSize(141, 41))
        self.save_pts_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.save_pts_button.setCheckable(False)
        self.save_pts_button.setObjectName("save_pts_button")
        self.horizontalLayout_3.addWidget(self.save_pts_button)
        self.draw_roi_layout.addLayout(self.horizontalLayout_3)
        self.save_roi_layout = QtWidgets.QGridLayout()
        self.save_roi_layout.setContentsMargins(-1, -1, -1, 10)
        self.save_roi_layout.setSpacing(10)
        self.save_roi_layout.setObjectName("save_roi_layout")
        self.save_folder_input = QtWidgets.QLineEdit(parent=constructRoi)
        self.save_folder_input.setMinimumSize(QtCore.QSize(201, 31))
        self.save_folder_input.setMaximumSize(QtCore.QSize(401, 31))
        self.save_folder_input.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.save_folder_input.setObjectName("save_folder_input")
        self.save_roi_layout.addWidget(self.save_folder_input, 0, 1, 1, 1)
        self.dest_folder_label = QtWidgets.QLabel(parent=constructRoi)
        self.dest_folder_label.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.dest_folder_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dest_folder_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.dest_folder_label.setObjectName("dest_folder_label")
        self.save_roi_layout.addWidget(self.dest_folder_label, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.roi_name_label = QtWidgets.QLabel(parent=constructRoi)
        self.roi_name_label.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.roi_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.roi_name_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.roi_name_label.setObjectName("roi_name_label")
        self.save_roi_layout.addWidget(self.roi_name_label, 2, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.save_name_input = QtWidgets.QLineEdit(parent=constructRoi)
        self.save_name_input.setMinimumSize(QtCore.QSize(201, 31))
        self.save_name_input.setMaximumSize(QtCore.QSize(401, 31))
        self.save_name_input.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.save_name_input.setObjectName("save_name_input")
        self.save_roi_layout.addWidget(self.save_name_input, 2, 1, 1, 1)
        self.chooseImageButtonsLayout_2 = QtWidgets.QHBoxLayout()
        self.chooseImageButtonsLayout_2.setSpacing(10)
        self.chooseImageButtonsLayout_2.setObjectName("chooseImageButtonsLayout_2")
        self.choose_save_folder_button = QtWidgets.QPushButton(parent=constructRoi)
        self.choose_save_folder_button.setMinimumSize(QtCore.QSize(131, 41))
        self.choose_save_folder_button.setMaximumSize(QtCore.QSize(131, 41))
        self.choose_save_folder_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.choose_save_folder_button.setObjectName("choose_save_folder_button")
        self.chooseImageButtonsLayout_2.addWidget(self.choose_save_folder_button)
        self.clear_save_folder_button = QtWidgets.QPushButton(parent=constructRoi)
        self.clear_save_folder_button.setMinimumSize(QtCore.QSize(131, 41))
        self.clear_save_folder_button.setMaximumSize(QtCore.QSize(131, 41))
        self.clear_save_folder_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clear_save_folder_button.setObjectName("clear_save_folder_button")
        self.chooseImageButtonsLayout_2.addWidget(self.clear_save_folder_button)
        self.save_roi_layout.addLayout(self.chooseImageButtonsLayout_2, 0, 2, 1, 1)
        self.chooseImageButtonsLayout_4 = QtWidgets.QHBoxLayout()
        self.chooseImageButtonsLayout_4.setObjectName("chooseImageButtonsLayout_4")
        self.save_roi_button = QtWidgets.QPushButton(parent=constructRoi)
        self.save_roi_button.setMinimumSize(QtCore.QSize(131, 41))
        self.save_roi_button.setMaximumSize(QtCore.QSize(131, 41))
        self.save_roi_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.save_roi_button.setObjectName("save_roi_button")
        self.chooseImageButtonsLayout_4.addWidget(self.save_roi_button)
        self.back_from_save_button = QtWidgets.QPushButton(parent=constructRoi)
        self.back_from_save_button.setMinimumSize(QtCore.QSize(131, 41))
        self.back_from_save_button.setMaximumSize(QtCore.QSize(131, 41))
        self.back_from_save_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.back_from_save_button.setObjectName("back_from_save_button")
        self.chooseImageButtonsLayout_4.addWidget(self.back_from_save_button)
        self.save_roi_layout.addLayout(self.chooseImageButtonsLayout_4, 2, 2, 1, 1)
        self.save_roi_layout.setColumnStretch(0, 1)
        self.save_roi_layout.setColumnStretch(1, 10)
        self.save_roi_layout.setColumnStretch(2, 10)
        self.save_roi_layout.setRowStretch(0, 1)
        self.save_roi_layout.setRowStretch(1, 10)
        self.save_roi_layout.setRowStretch(2, 10)
        self.draw_roi_layout.addLayout(self.save_roi_layout)
        self.im_display_frame = QtWidgets.QFrame(parent=constructRoi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.im_display_frame.sizePolicy().hasHeightForWidth())
        self.im_display_frame.setSizePolicy(sizePolicy)
        self.im_display_frame.setMinimumSize(QtCore.QSize(501, 321))
        self.im_display_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.im_display_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.im_display_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.im_display_frame.setObjectName("im_display_frame")
        self.draw_roi_layout.addWidget(self.im_display_frame)
        self.rect_dims_layout = QtWidgets.QHBoxLayout()
        self.rect_dims_layout.setObjectName("rect_dims_layout")
        self.physical_roi_dims_label = QtWidgets.QLabel(parent=constructRoi)
        self.physical_roi_dims_label.setMinimumSize(QtCore.QSize(200, 0))
        self.physical_roi_dims_label.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.physical_roi_dims_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.physical_roi_dims_label.setScaledContents(False)
        self.physical_roi_dims_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.physical_roi_dims_label.setWordWrap(True)
        self.physical_roi_dims_label.setObjectName("physical_roi_dims_label")
        self.rect_dims_layout.addWidget(self.physical_roi_dims_label)
        self.physical_roi_width_label = QtWidgets.QLabel(parent=constructRoi)
        self.physical_roi_width_label.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.physical_roi_width_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.physical_roi_width_label.setScaledContents(False)
        self.physical_roi_width_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.physical_roi_width_label.setWordWrap(True)
        self.physical_roi_width_label.setObjectName("physical_roi_width_label")
        self.rect_dims_layout.addWidget(self.physical_roi_width_label, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.physical_roi_width_val = QtWidgets.QLabel(parent=constructRoi)
        self.physical_roi_width_val.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.physical_roi_width_val.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.physical_roi_width_val.setScaledContents(False)
        self.physical_roi_width_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.physical_roi_width_val.setWordWrap(True)
        self.physical_roi_width_val.setObjectName("physical_roi_width_val")
        self.rect_dims_layout.addWidget(self.physical_roi_width_val)
        self.physical_roi_height_label = QtWidgets.QLabel(parent=constructRoi)
        self.physical_roi_height_label.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.physical_roi_height_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.physical_roi_height_label.setScaledContents(False)
        self.physical_roi_height_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.physical_roi_height_label.setWordWrap(True)
        self.physical_roi_height_label.setObjectName("physical_roi_height_label")
        self.rect_dims_layout.addWidget(self.physical_roi_height_label, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.physical_roi_height_val = QtWidgets.QLabel(parent=constructRoi)
        self.physical_roi_height_val.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.physical_roi_height_val.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.physical_roi_height_val.setScaledContents(False)
        self.physical_roi_height_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.physical_roi_height_val.setWordWrap(True)
        self.physical_roi_height_val.setObjectName("physical_roi_height_val")
        self.rect_dims_layout.addWidget(self.physical_roi_height_val)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.rect_dims_layout.addItem(spacerItem2)
        self.rect_dims_layout.setStretch(0, 1)
        self.rect_dims_layout.setStretch(1, 1)
        self.rect_dims_layout.setStretch(2, 2)
        self.rect_dims_layout.setStretch(3, 1)
        self.rect_dims_layout.setStretch(4, 2)
        self.draw_roi_layout.addLayout(self.rect_dims_layout)
        self.draw_roi_layout.setStretch(0, 1)
        self.full_screen_layout.addLayout(self.draw_roi_layout)
        self.main_layout.addLayout(self.full_screen_layout)

        self.retranslateUi(constructRoi)
        QtCore.QMetaObject.connectSlotsByName(constructRoi)

    def retranslateUi(self, constructRoi):
        _translate = QtCore.QCoreApplication.translate
        constructRoi.setWindowTitle(_translate("constructRoi", "Select Region of Interest"))
        self.sidebar.setToolTip(_translate("constructRoi", "<html><head/><body><p><br/></p></body></html>"))
        self.imageSelectionLabelSidebar.setText(_translate("constructRoi", "Image Selection:"))
        self.imageLabel.setText(_translate("constructRoi", "Image:"))
        self.phantomLabel.setText(_translate("constructRoi", "Phantom:"))
        self.image_path_input.setText(_translate("constructRoi", "Sample filename "))
        self.phantom_path_input.setText(_translate("constructRoi", "Sample filename "))
        self.roiSidebarLabel.setText(_translate("constructRoi", "Segmentation Selection"))
        self.rfAnalysisLabel.setText(_translate("constructRoi", "QUS Analysis"))
        self.exportResultsLabel.setText(_translate("constructRoi", "Visualization / Export"))
        self.analysisParamsLabel.setText(_translate("constructRoi", "Analysis Parameter Selection"))
        self.back_button.setText(_translate("constructRoi", "Back"))
        self.loading_screen_label.setText(_translate("constructRoi", "LOADING...."))
        self.physical_dims_label.setText(_translate("constructRoi", "Physical Dims (cm):"))
        self.physical_depth_label.setText(_translate("constructRoi", "Depth:"))
        self.physical_width_val.setText(_translate("constructRoi", "0"))
        self.physical_depth_val.setText(_translate("constructRoi", "0"))
        self.physical_width_label.setText(_translate("constructRoi", "Width:"))
        self.construct_roi_label.setText(_translate("constructRoi", "Construct Region of Interest (ROI):"))
        self.pixel_dims_label.setText(_translate("constructRoi", "Pixel Dims:"))
        self.pixel_width_label.setText(_translate("constructRoi", "Width:"))
        self.pixel_depth_label.setText(_translate("constructRoi", "Depth:"))
        self.pixel_width_val.setText(_translate("constructRoi", "0"))
        self.pixel_depth_val.setText(_translate("constructRoi", "0"))
        self.brightness_label.setText(_translate("constructRoi", "Brightness:"))
        self.brightness_value_label.setText(_translate("constructRoi", "0"))
        self.dicom_overlay_checkbox.setText(_translate("constructRoi", "Show DICOM Overlay"))
        self.transparency_label.setText(_translate("constructRoi", "Transparency:"))
        self.transparency_value_label.setText(_translate("constructRoi", "50"))
        self.load_dicom_button.setText(_translate("constructRoi", "Load DICOM File"))
        self.back_from_drag_button.setText(_translate("constructRoi", "Back"))
        self.save_drag_button.setText(_translate("constructRoi", "Save ROI"))
        self.draw_pts_type_button.setText(_translate("constructRoi", "Draw Freehand w Points"))
        self.draw_freehand_drag_type_button.setText(_translate("constructRoi", "Draw Freehand by Dragging"))
        self.draw_rect_drag_type_button.setText(_translate("constructRoi", "Draw Rectangle by Dragging"))
        self.clear_roi_button.setText(_translate("constructRoi", "Clear ROI"))
        self.undo_last_pt_button.setText(_translate("constructRoi", "Undo Last Point"))
        self.close_roi_button.setText(_translate("constructRoi", "Close ROI"))
        self.back_from_pts_button.setText(_translate("constructRoi", "Back"))
        self.save_pts_button.setText(_translate("constructRoi", "Save ROI"))
        self.dest_folder_label.setText(_translate("constructRoi", "Dest Folder"))
        self.roi_name_label.setText(_translate("constructRoi", "ROI Name"))
        self.choose_save_folder_button.setText(_translate("constructRoi", "Choose Folder"))
        self.clear_save_folder_button.setText(_translate("constructRoi", "Clear Path"))
        self.save_roi_button.setText(_translate("constructRoi", "Save"))
        self.back_from_save_button.setText(_translate("constructRoi", "Back"))
        self.physical_roi_dims_label.setText(_translate("constructRoi", "Rect. Dims (cm):"))
        self.physical_roi_width_label.setText(_translate("constructRoi", "Width:"))
        self.physical_roi_width_val.setText(_translate("constructRoi", "0"))
        self.physical_roi_height_label.setText(_translate("constructRoi", "Depth"))
        self.physical_roi_height_val.setText(_translate("constructRoi", "0"))
