# Form implementation generated from reading ui file 'D:\Omid\0_main\05.01.2026\5_QuantUS-OpenSource\QuantUS\src\qus\visualization_loading\ui\visualization_function_selection.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_visualizationFunctionSelection(object):
    def setupUi(self, visualizationFunctionSelection):
        visualizationFunctionSelection.setObjectName("visualizationFunctionSelection")
        visualizationFunctionSelection.resize(1400, 1070)
        visualizationFunctionSelection.setMinimumSize(QtCore.QSize(1400, 662))
        visualizationFunctionSelection.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=visualizationFunctionSelection)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(50, 10, 1151, 801))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.full_screen_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.full_screen_layout.setContentsMargins(0, 0, 0, 0)
        self.full_screen_layout.setObjectName("full_screen_layout")
        self.side_bar_layout = QtWidgets.QVBoxLayout()
        self.side_bar_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.side_bar_layout.setSpacing(0)
        self.side_bar_layout.setObjectName("side_bar_layout")
        self.sidebar = QtWidgets.QWidget(parent=self.horizontalLayoutWidget_4)
        self.sidebar.setMinimumSize(QtCore.QSize(341, 601))
        self.sidebar.setMaximumSize(QtCore.QSize(241, 601))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.imageSelectionSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.imageSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.imageSelectionSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.imageSelectionSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.imageSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.imageSelectionSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.imageSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.imageSelectionSidebar.setObjectName("imageSelectionSidebar")
        self.imageSelectionLabelSidebar = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.imageSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.imageSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageSelectionLabelSidebar.setObjectName("imageSelectionLabelSidebar")
        self.imageLabel = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.imageLabel.setGeometry(QtCore.QRect(-60, 40, 191, 51))
        self.imageLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.phantomLabel = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.phantomLabel.setGeometry(QtCore.QRect(-50, 70, 191, 51))
        self.phantomLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold\n"
"}")
        self.phantomLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.phantomLabel.setObjectName("phantomLabel")
        self.image_path_input = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.image_path_input.setGeometry(QtCore.QRect(100, 40, 241, 51))
        self.image_path_input.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.image_path_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.image_path_input.setObjectName("image_path_input")
        self.phantom_path_input = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.phantom_path_input.setGeometry(QtCore.QRect(100, 70, 241, 51))
        self.phantom_path_input.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.phantom_path_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.phantom_path_input.setObjectName("phantom_path_input")
        self.segmentationSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.segmentationSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.segmentationSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.segmentationSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.segmentationSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.segmentationSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.segmentationSidebar.setObjectName("segmentationSidebar")
        self.segmentationSidebarLabel = QtWidgets.QLabel(parent=self.segmentationSidebar)
        self.segmentationSidebarLabel.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.segmentationSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.segmentationSidebarLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.segmentationSidebarLabel.setObjectName("segmentationSidebarLabel")
        self.analysisParamsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.analysisParamsSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisParamsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.analysisParamsSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisParamsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.analysisParamsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.analysisParamsSidebar.setObjectName("analysisParamsSidebar")
        self.analysisParamsLabel = QtWidgets.QLabel(parent=self.analysisParamsSidebar)
        self.analysisParamsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisParamsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisParamsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.analysisParamsLabel.setObjectName("analysisParamsLabel")
        self.rfAnalysisSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.rfAnalysisSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.rfAnalysisSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.rfAnalysisSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.rfAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.rfAnalysisSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rfAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rfAnalysisSidebar.setObjectName("rfAnalysisSidebar")
        self.rfAnalysisLabel = QtWidgets.QLabel(parent=self.rfAnalysisSidebar)
        self.rfAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.rfAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.rfAnalysisLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rfAnalysisLabel.setObjectName("rfAnalysisLabel")
        self.exportResultsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.exportResultsSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.exportResultsSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.exportResultsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.exportResultsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.exportResultsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.exportResultsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.exportResultsSidebar.setObjectName("exportResultsSidebar")
        self.exportResultsLabel = QtWidgets.QLabel(parent=self.exportResultsSidebar)
        self.exportResultsLabel.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.exportResultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.exportResultsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exportResultsLabel.setObjectName("exportResultsLabel")
        self.side_bar_layout.addWidget(self.sidebar)
        self.gridFrame = QtWidgets.QFrame(parent=self.horizontalLayoutWidget_4)
        self.gridFrame.setMaximumSize(QtCore.QSize(341, 16777215))
        self.gridFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.gridFrame.setObjectName("gridFrame")
        self.backButtonGrid = QtWidgets.QGridLayout(self.gridFrame)
        self.backButtonGrid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.backButtonGrid.setContentsMargins(10, 10, 10, 10)
        self.backButtonGrid.setObjectName("backButtonGrid")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.backButtonGrid.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.backButtonGrid.addItem(spacerItem1, 1, 1, 1, 1)
        self.back_button = QtWidgets.QPushButton(parent=self.gridFrame)
        self.back_button.setMinimumSize(QtCore.QSize(131, 41))
        self.back_button.setMaximumSize(QtCore.QSize(131, 41))
        self.back_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.backButtonGrid.addWidget(self.back_button, 1, 0, 1, 1)
        self.side_bar_layout.addWidget(self.gridFrame)
        self.full_screen_layout.addLayout(self.side_bar_layout)
        self.visualization_function_layout = QtWidgets.QVBoxLayout()
        self.visualization_function_layout.setContentsMargins(30, 30, 10, 10)
        self.visualization_function_layout.setSpacing(20)
        self.visualization_function_layout.setObjectName("visualization_function_layout")
        self.analysis_function_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.analysis_function_label.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.analysis_function_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.analysis_function_label.setScaledContents(False)
        self.analysis_function_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.analysis_function_label.setWordWrap(True)
        self.analysis_function_label.setObjectName("analysis_function_label")
        self.visualization_function_layout.addWidget(self.analysis_function_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.funcs_list = QtWidgets.QListWidget(parent=self.horizontalLayoutWidget_4)
        self.funcs_list.setObjectName("funcs_list")
        self.horizontalLayout.addWidget(self.funcs_list)
        self.chooseImgLayout = QtWidgets.QVBoxLayout()
        self.chooseImgLayout.setContentsMargins(5, -1, 5, -1)
        self.chooseImgLayout.setObjectName("chooseImgLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.chooseImgLayout.addItem(spacerItem2)
        self.dest_path_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.dest_path_label.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.dest_path_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dest_path_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.dest_path_label.setObjectName("dest_path_label")
        self.chooseImgLayout.addWidget(self.dest_path_label)
        self.dest_path_input = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_4)
        self.dest_path_input.setMinimumSize(QtCore.QSize(201, 31))
        self.dest_path_input.setMaximumSize(QtCore.QSize(401, 31))
        self.dest_path_input.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.dest_path_input.setObjectName("dest_path_input")
        self.chooseImgLayout.addWidget(self.dest_path_input, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.chooseImageButtonsLayout = QtWidgets.QHBoxLayout()
        self.chooseImageButtonsLayout.setSpacing(1)
        self.chooseImageButtonsLayout.setObjectName("chooseImageButtonsLayout")
        self.choose_dest_path_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.choose_dest_path_button.setMinimumSize(QtCore.QSize(131, 41))
        self.choose_dest_path_button.setMaximumSize(QtCore.QSize(131, 41))
        self.choose_dest_path_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.choose_dest_path_button.setObjectName("choose_dest_path_button")
        self.chooseImageButtonsLayout.addWidget(self.choose_dest_path_button, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.clear_dest_path_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.clear_dest_path_button.setMinimumSize(QtCore.QSize(131, 41))
        self.clear_dest_path_button.setMaximumSize(QtCore.QSize(131, 41))
        self.clear_dest_path_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clear_dest_path_button.setObjectName("clear_dest_path_button")
        self.chooseImageButtonsLayout.addWidget(self.clear_dest_path_button)
        self.chooseImgLayout.addLayout(self.chooseImageButtonsLayout)
        self.clear_dest_path_hint = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.clear_dest_path_hint.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.clear_dest_path_hint.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.clear_dest_path_hint.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.clear_dest_path_hint.setObjectName("clear_dest_path_hint")
        self.chooseImgLayout.addWidget(self.clear_dest_path_hint)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.chooseImgLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.chooseImgLayout)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 1)
        self.visualization_function_layout.addLayout(self.horizontalLayout)
        self.next_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.next_button.setMinimumSize(QtCore.QSize(131, 41))
        self.next_button.setMaximumSize(QtCore.QSize(131, 41))
        self.next_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.next_button.setObjectName("next_button")
        self.visualization_function_layout.addWidget(self.next_button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.visualization_function_layout.addItem(spacerItem4)
        self.visualization_function_layout.setStretch(0, 1)
        self.visualization_function_layout.setStretch(1, 10)
        self.visualization_function_layout.setStretch(2, 1)
        self.visualization_function_layout.setStretch(3, 1)
        self.full_screen_layout.addLayout(self.visualization_function_layout)

        self.retranslateUi(visualizationFunctionSelection)
        QtCore.QMetaObject.connectSlotsByName(visualizationFunctionSelection)

    def retranslateUi(self, visualizationFunctionSelection):
        _translate = QtCore.QCoreApplication.translate
        visualizationFunctionSelection.setWindowTitle(_translate("visualizationFunctionSelection", "Visualization Configuration Loading"))
        self.sidebar.setToolTip(_translate("visualizationFunctionSelection", "<html><head/><body><p><br/></p></body></html>"))
        self.imageSelectionLabelSidebar.setText(_translate("visualizationFunctionSelection", "Image Selection:"))
        self.imageLabel.setText(_translate("visualizationFunctionSelection", "Image:"))
        self.phantomLabel.setText(_translate("visualizationFunctionSelection", "Phantom:"))
        self.image_path_input.setText(_translate("visualizationFunctionSelection", "Sample filename "))
        self.phantom_path_input.setText(_translate("visualizationFunctionSelection", "Sample filename "))
        self.segmentationSidebarLabel.setText(_translate("visualizationFunctionSelection", "Segmentation Selection"))
        self.analysisParamsLabel.setText(_translate("visualizationFunctionSelection", "Analysis Parameter Selection"))
        self.rfAnalysisLabel.setText(_translate("visualizationFunctionSelection", "QUS Analysis"))
        self.exportResultsLabel.setText(_translate("visualizationFunctionSelection", "Visualization / Export"))
        self.back_button.setText(_translate("visualizationFunctionSelection", "Back"))
        self.analysis_function_label.setText(_translate("visualizationFunctionSelection", "Select visualization functions to run:"))
        self.dest_path_label.setText(_translate("visualizationFunctionSelection", "Destination folder:"))
        self.choose_dest_path_button.setText(_translate("visualizationFunctionSelection", "Choose File"))
        self.clear_dest_path_button.setText(_translate("visualizationFunctionSelection", "Clear Path"))
        self.clear_dest_path_hint.setText(_translate("visualizationFunctionSelection", "\n"
"Default destination folder\n"
"saves results internally.\n"
"Modify for persistent exporting."))
        self.next_button.setText(_translate("visualizationFunctionSelection", "Next"))
