# Form implementation generated from reading ui file 'D:\Omid\0_main\05.01.2026\5_QuantUS-OpenSource\QuantUS\src\ceus\image_loading\ui\scan_type.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_select_scan_type(object):
    def setupUi(self, select_scan_type):
        select_scan_type.setObjectName("select_scan_type")
        select_scan_type.resize(1512, 893)
        select_scan_type.setMinimumSize(QtCore.QSize(201, 31))
        select_scan_type.setMaximumSize(QtCore.QSize(16777215, 16777215))
        select_scan_type.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=select_scan_type)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 10, 1545, 844))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.full_screen_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.full_screen_layout.setContentsMargins(0, 0, 0, 0)
        self.full_screen_layout.setObjectName("full_screen_layout")
        self.side_bar_layout = QtWidgets.QVBoxLayout()
        self.side_bar_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.side_bar_layout.setSpacing(0)
        self.side_bar_layout.setObjectName("side_bar_layout")
        self.sidebar = QtWidgets.QWidget(parent=self.horizontalLayoutWidget)
        self.sidebar.setMinimumSize(QtCore.QSize(341, 601))
        self.sidebar.setMaximumSize(QtCore.QSize(241, 601))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.scanSelectionSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.scanSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.scanSelectionSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.scanSelectionSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.scanSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.scanSelectionSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.scanSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.scanSelectionSidebar.setObjectName("scanSelectionSidebar")
        self.scanSelectionLabelSidebar = QtWidgets.QLabel(parent=self.scanSelectionSidebar)
        self.scanSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.scanSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.scanSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scanSelectionLabelSidebar.setObjectName("scanSelectionLabelSidebar")
        self.scanLabel = QtWidgets.QLabel(parent=self.scanSelectionSidebar)
        self.scanLabel.setGeometry(QtCore.QRect(-60, 50, 191, 51))
        self.scanLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.scanLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scanLabel.setObjectName("scanLabel")
        self.segSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.segSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.segSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.segSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.segSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.segSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.segSidebar.setObjectName("segSidebar")
        self.segSidebarLabel = QtWidgets.QLabel(parent=self.segSidebar)
        self.segSidebarLabel.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.segSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.segSidebarLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.segSidebarLabel.setObjectName("segSidebarLabel")
        self.resultsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.resultsSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.resultsSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.resultsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.resultsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.resultsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.resultsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.resultsSidebar.setObjectName("resultsSidebar")
        self.resultsLabel = QtWidgets.QLabel(parent=self.resultsSidebar)
        self.resultsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.resultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.resultsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.resultsLabel.setObjectName("resultsLabel")
        self.visualizationsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.visualizationsSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.visualizationsSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.visualizationsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.visualizationsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.visualizationsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.visualizationsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.visualizationsSidebar.setObjectName("visualizationsSidebar")
        self.visualizationsLabel = QtWidgets.QLabel(parent=self.visualizationsSidebar)
        self.visualizationsLabel.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.visualizationsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.visualizationsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.visualizationsLabel.setObjectName("visualizationsLabel")
        self.analysisConfigSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.analysisConfigSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisConfigSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.analysisConfigSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisConfigSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.analysisConfigSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.analysisConfigSidebar.setObjectName("analysisConfigSidebar")
        self.analysisConfigLabel = QtWidgets.QLabel(parent=self.analysisConfigSidebar)
        self.analysisConfigLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisConfigLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisConfigLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.analysisConfigLabel.setObjectName("analysisConfigLabel")
        self.side_bar_layout.addWidget(self.sidebar)
        self.gridFrame = QtWidgets.QFrame(parent=self.horizontalLayoutWidget)
        self.gridFrame.setMinimumSize(QtCore.QSize(341, 0))
        self.gridFrame.setMaximumSize(QtCore.QSize(341, 16777215))
        self.gridFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.gridFrame.setObjectName("gridFrame")
        self.backButtonGrid = QtWidgets.QGridLayout(self.gridFrame)
        self.backButtonGrid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.backButtonGrid.setContentsMargins(10, 10, 10, 10)
        self.backButtonGrid.setObjectName("backButtonGrid")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.backButtonGrid.addItem(spacerItem, 0, 0, 1, 1)
        self.side_bar_layout.addWidget(self.gridFrame)
        self.full_screen_layout.addLayout(self.side_bar_layout)
        self.select_type_layout = QtWidgets.QVBoxLayout()
        self.select_type_layout.setContentsMargins(30, -1, 30, -1)
        self.select_type_layout.setSpacing(50)
        self.select_type_layout.setObjectName("select_type_layout")
        self.select_type_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.select_type_label.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.select_type_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.select_type_label.setScaledContents(False)
        self.select_type_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.select_type_label.setWordWrap(True)
        self.select_type_label.setObjectName("select_type_label")
        self.select_type_layout.addWidget(self.select_type_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.scan_type_dropdown = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget)
        self.scan_type_dropdown.setMinimumSize(QtCore.QSize(180, 41))
        self.scan_type_dropdown.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.scan_type_dropdown.setFont(font)
        self.scan_type_dropdown.setStyleSheet("QComboBox {\n"
"    color: white;\n"
"}")
        self.scan_type_dropdown.setObjectName("scan_type_dropdown")
        self.select_type_layout.addWidget(self.scan_type_dropdown)
        self.accept_type_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.accept_type_button.setMinimumSize(QtCore.QSize(131, 41))
        self.accept_type_button.setMaximumSize(QtCore.QSize(131, 41))
        self.accept_type_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.accept_type_button.setObjectName("accept_type_button")
        self.select_type_layout.addWidget(self.accept_type_button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.select_type_layout.addItem(spacerItem1)
        self.select_type_layout.setStretch(0, 2)
        self.select_type_layout.setStretch(1, 2)
        self.select_type_layout.setStretch(2, 2)
        self.select_type_layout.setStretch(3, 1)
        self.full_screen_layout.addLayout(self.select_type_layout)
        self.full_screen_layout.setStretch(0, 1)
        self.full_screen_layout.setStretch(1, 5)

        self.retranslateUi(select_scan_type)
        QtCore.QMetaObject.connectSlotsByName(select_scan_type)

    def retranslateUi(self, select_scan_type):
        _translate = QtCore.QCoreApplication.translate
        select_scan_type.setWindowTitle(_translate("select_scan_type", "Select Ultrasound Scan"))
        self.sidebar.setToolTip(_translate("select_scan_type", "<html><head/><body><p><br/></p></body></html>"))
        self.scanSelectionLabelSidebar.setText(_translate("select_scan_type", "Scan Selection:"))
        self.scanLabel.setText(_translate("select_scan_type", "Scan:"))
        self.segSidebarLabel.setText(_translate("select_scan_type", "Segmentation Selection"))
        self.resultsLabel.setText(_translate("select_scan_type", "Results"))
        self.visualizationsLabel.setText(_translate("select_scan_type", "Visualizations"))
        self.analysisConfigLabel.setText(_translate("select_scan_type", "Analysis Configuration"))
        self.select_type_label.setText(_translate("select_scan_type", "Select Data Type:"))
        self.accept_type_button.setText(_translate("select_scan_type", "Accept"))
