# Form implementation generated from reading ui file 'D:\Omid\0_main\05.01.2026\5_QuantUS-OpenSource\QuantUS\src\ceus\seg_loading\ui\draw_voi.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_voi_drawer(object):
    def setupUi(self, voi_drawer):
        voi_drawer.setObjectName("voi_drawer")
        voi_drawer.resize(1512, 832)
        voi_drawer.setMinimumSize(QtCore.QSize(0, 0))
        voi_drawer.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=voi_drawer)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, -250, 1351, 951))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.full_screen_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.full_screen_layout.setContentsMargins(0, 0, 0, 0)
        self.full_screen_layout.setObjectName("full_screen_layout")
        self.side_bar_layout = QtWidgets.QVBoxLayout()
        self.side_bar_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.side_bar_layout.setSpacing(0)
        self.side_bar_layout.setObjectName("side_bar_layout")
        self.sidebar = QtWidgets.QWidget(parent=self.horizontalLayoutWidget_4)
        self.sidebar.setMinimumSize(QtCore.QSize(341, 601))
        self.sidebar.setMaximumSize(QtCore.QSize(241, 601))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.scanSelectionSidebar_2 = QtWidgets.QFrame(parent=self.sidebar)
        self.scanSelectionSidebar_2.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.scanSelectionSidebar_2.setMinimumSize(QtCore.QSize(341, 121))
        self.scanSelectionSidebar_2.setMaximumSize(QtCore.QSize(341, 121))
        self.scanSelectionSidebar_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.scanSelectionSidebar_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.scanSelectionSidebar_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.scanSelectionSidebar_2.setObjectName("scanSelectionSidebar_2")
        self.scanSelectionLabelSidebar_2 = QtWidgets.QLabel(parent=self.scanSelectionSidebar_2)
        self.scanSelectionLabelSidebar_2.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.scanSelectionLabelSidebar_2.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.scanSelectionLabelSidebar_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scanSelectionLabelSidebar_2.setObjectName("scanSelectionLabelSidebar_2")
        self.scanLabel_2 = QtWidgets.QLabel(parent=self.scanSelectionSidebar_2)
        self.scanLabel_2.setGeometry(QtCore.QRect(-60, 50, 191, 51))
        self.scanLabel_2.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.scanLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scanLabel_2.setObjectName("scanLabel_2")
        self.scan_name_input = QtWidgets.QLabel(parent=self.scanSelectionSidebar_2)
        self.scan_name_input.setGeometry(QtCore.QRect(70, 50, 261, 51))
        self.scan_name_input.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.scan_name_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.scan_name_input.setObjectName("scan_name_input")
        self.segSidebar_2 = QtWidgets.QFrame(parent=self.sidebar)
        self.segSidebar_2.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.segSidebar_2.setMaximumSize(QtCore.QSize(341, 121))
        self.segSidebar_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.segSidebar_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.segSidebar_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.segSidebar_2.setObjectName("segSidebar_2")
        self.segSidebarLabel_2 = QtWidgets.QLabel(parent=self.segSidebar_2)
        self.segSidebarLabel_2.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.segSidebarLabel_2.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.segSidebarLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.segSidebarLabel_2.setObjectName("segSidebarLabel_2")
        self.resultsSidebar_2 = QtWidgets.QFrame(parent=self.sidebar)
        self.resultsSidebar_2.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.resultsSidebar_2.setMinimumSize(QtCore.QSize(341, 121))
        self.resultsSidebar_2.setMaximumSize(QtCore.QSize(341, 121))
        self.resultsSidebar_2.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.resultsSidebar_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.resultsSidebar_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.resultsSidebar_2.setObjectName("resultsSidebar_2")
        self.resultsLabel_2 = QtWidgets.QLabel(parent=self.resultsSidebar_2)
        self.resultsLabel_2.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.resultsLabel_2.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.resultsLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.resultsLabel_2.setObjectName("resultsLabel_2")
        self.visualizationsSidebar_2 = QtWidgets.QFrame(parent=self.sidebar)
        self.visualizationsSidebar_2.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.visualizationsSidebar_2.setMinimumSize(QtCore.QSize(341, 121))
        self.visualizationsSidebar_2.setMaximumSize(QtCore.QSize(341, 121))
        self.visualizationsSidebar_2.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.visualizationsSidebar_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.visualizationsSidebar_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.visualizationsSidebar_2.setObjectName("visualizationsSidebar_2")
        self.visualizationsLabel_2 = QtWidgets.QLabel(parent=self.visualizationsSidebar_2)
        self.visualizationsLabel_2.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.visualizationsLabel_2.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.visualizationsLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.visualizationsLabel_2.setObjectName("visualizationsLabel_2")
        self.analysisConfigSidebar_2 = QtWidgets.QFrame(parent=self.sidebar)
        self.analysisConfigSidebar_2.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisConfigSidebar_2.setMaximumSize(QtCore.QSize(341, 121))
        self.analysisConfigSidebar_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisConfigSidebar_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.analysisConfigSidebar_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.analysisConfigSidebar_2.setObjectName("analysisConfigSidebar_2")
        self.analysisConfigLabel_2 = QtWidgets.QLabel(parent=self.analysisConfigSidebar_2)
        self.analysisConfigLabel_2.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisConfigLabel_2.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisConfigLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.analysisConfigLabel_2.setObjectName("analysisConfigLabel_2")
        self.side_bar_layout.addWidget(self.sidebar)
        self.gridFrame_3 = QtWidgets.QFrame(parent=self.horizontalLayoutWidget_4)
        self.gridFrame_3.setMinimumSize(QtCore.QSize(341, 0))
        self.gridFrame_3.setMaximumSize(QtCore.QSize(341, 16777215))
        self.gridFrame_3.setStyleSheet("QFrame {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.gridFrame_3.setObjectName("gridFrame_3")
        self.backButtonGrid_4 = QtWidgets.QGridLayout(self.gridFrame_3)
        self.backButtonGrid_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.backButtonGrid_4.setContentsMargins(10, 10, 10, 10)
        self.backButtonGrid_4.setObjectName("backButtonGrid_4")
        self.observing_label = QtWidgets.QLabel(parent=self.gridFrame_3)
        self.observing_label.setStyleSheet("QLabel { background-color : rgb(42, 42, 42); color : red; }")
        self.observing_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.observing_label.setObjectName("observing_label")
        self.backButtonGrid_4.addWidget(self.observing_label, 0, 0, 1, 1)
        self.navigating_label = QtWidgets.QLabel(parent=self.gridFrame_3)
        self.navigating_label.setStyleSheet("QLabel { background-color : rgb(42, 42, 42); color : green; }")
        self.navigating_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.navigating_label.setObjectName("navigating_label")
        self.backButtonGrid_4.addWidget(self.navigating_label, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.backButtonGrid_4.addItem(spacerItem, 3, 1, 1, 1)
        self.back_button = QtWidgets.QPushButton(parent=self.gridFrame_3)
        self.back_button.setMinimumSize(QtCore.QSize(131, 41))
        self.back_button.setMaximumSize(QtCore.QSize(131, 41))
        self.back_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.backButtonGrid_4.addWidget(self.back_button, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.backButtonGrid_4.addItem(spacerItem1, 2, 0, 1, 1)
        self.toggle_crosshair_visibility_button = QtWidgets.QPushButton(parent=self.gridFrame_3)
        self.toggle_crosshair_visibility_button.setMinimumSize(QtCore.QSize(131, 41))
        self.toggle_crosshair_visibility_button.setMaximumSize(QtCore.QSize(131, 41))
        self.toggle_crosshair_visibility_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.toggle_crosshair_visibility_button.setObjectName("toggle_crosshair_visibility_button")
        self.backButtonGrid_4.addWidget(self.toggle_crosshair_visibility_button, 3, 2, 1, 1)
        self.side_bar_layout.addWidget(self.gridFrame_3)
        self.full_screen_layout.addLayout(self.side_bar_layout)
        self.voi_layout = QtWidgets.QGridLayout()
        self.voi_layout.setObjectName("voi_layout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sag_plane_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sag_plane_label.sizePolicy().hasHeightForWidth())
        self.sag_plane_label.setSizePolicy(sizePolicy)
        self.sag_plane_label.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.sag_plane_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sag_plane_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.sag_plane_label.setObjectName("sag_plane_label")
        self.verticalLayout_6.addWidget(self.sag_plane_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.sag_plane = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sag_plane.sizePolicy().hasHeightForWidth())
        self.sag_plane.setSizePolicy(sizePolicy)
        self.sag_plane.setMinimumSize(QtCore.QSize(321, 301))
        self.sag_plane.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.sag_plane.setMouseTracking(True)
        self.sag_plane.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.sag_plane.setText("")
        self.sag_plane.setObjectName("sag_plane")
        self.verticalLayout_6.addWidget(self.sag_plane)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sag_frame_num = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sag_frame_num.sizePolicy().hasHeightForWidth())
        self.sag_frame_num.setSizePolicy(sizePolicy)
        self.sag_frame_num.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.sag_frame_num.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sag_frame_num.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.sag_frame_num.setObjectName("sag_frame_num")
        self.horizontalLayout_7.addWidget(self.sag_frame_num, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.sag_of_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sag_of_label.sizePolicy().hasHeightForWidth())
        self.sag_of_label.setSizePolicy(sizePolicy)
        self.sag_of_label.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.sag_of_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sag_of_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.sag_of_label.setObjectName("sag_of_label")
        self.horizontalLayout_7.addWidget(self.sag_of_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.sag_total_frames = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sag_total_frames.sizePolicy().hasHeightForWidth())
        self.sag_total_frames.setSizePolicy(sizePolicy)
        self.sag_total_frames.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.sag_total_frames.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.sag_total_frames.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.sag_total_frames.setObjectName("sag_total_frames")
        self.horizontalLayout_7.addWidget(self.sag_total_frames, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.voi_layout.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ax_plane_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ax_plane_label.sizePolicy().hasHeightForWidth())
        self.ax_plane_label.setSizePolicy(sizePolicy)
        self.ax_plane_label.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.ax_plane_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ax_plane_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.ax_plane_label.setObjectName("ax_plane_label")
        self.verticalLayout_4.addWidget(self.ax_plane_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ax_plane = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ax_plane.sizePolicy().hasHeightForWidth())
        self.ax_plane.setSizePolicy(sizePolicy)
        self.ax_plane.setMinimumSize(QtCore.QSize(321, 301))
        self.ax_plane.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.ax_plane.setMouseTracking(True)
        self.ax_plane.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.ax_plane.setText("")
        self.ax_plane.setObjectName("ax_plane")
        self.verticalLayout_4.addWidget(self.ax_plane)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ax_frame_num = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ax_frame_num.sizePolicy().hasHeightForWidth())
        self.ax_frame_num.setSizePolicy(sizePolicy)
        self.ax_frame_num.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.ax_frame_num.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ax_frame_num.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.ax_frame_num.setObjectName("ax_frame_num")
        self.horizontalLayout_6.addWidget(self.ax_frame_num, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ax_of_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ax_of_label.sizePolicy().hasHeightForWidth())
        self.ax_of_label.setSizePolicy(sizePolicy)
        self.ax_of_label.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.ax_of_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ax_of_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.ax_of_label.setObjectName("ax_of_label")
        self.horizontalLayout_6.addWidget(self.ax_of_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ax_total_frames = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ax_total_frames.sizePolicy().hasHeightForWidth())
        self.ax_total_frames.setSizePolicy(sizePolicy)
        self.ax_total_frames.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.ax_total_frames.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ax_total_frames.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.ax_total_frames.setObjectName("ax_total_frames")
        self.horizontalLayout_6.addWidget(self.ax_total_frames, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.voi_layout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cor_plane_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cor_plane_label.sizePolicy().hasHeightForWidth())
        self.cor_plane_label.setSizePolicy(sizePolicy)
        self.cor_plane_label.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.cor_plane_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cor_plane_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.cor_plane_label.setObjectName("cor_plane_label")
        self.verticalLayout_7.addWidget(self.cor_plane_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.cor_plane = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.cor_plane.sizePolicy().hasHeightForWidth())
        self.cor_plane.setSizePolicy(sizePolicy)
        self.cor_plane.setMinimumSize(QtCore.QSize(321, 301))
        self.cor_plane.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.cor_plane.setMouseTracking(True)
        self.cor_plane.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.cor_plane.setText("")
        self.cor_plane.setObjectName("cor_plane")
        self.verticalLayout_7.addWidget(self.cor_plane)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cor_frame_num = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cor_frame_num.sizePolicy().hasHeightForWidth())
        self.cor_frame_num.setSizePolicy(sizePolicy)
        self.cor_frame_num.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.cor_frame_num.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cor_frame_num.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.cor_frame_num.setObjectName("cor_frame_num")
        self.horizontalLayout_8.addWidget(self.cor_frame_num, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.cor_of_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cor_of_label.sizePolicy().hasHeightForWidth())
        self.cor_of_label.setSizePolicy(sizePolicy)
        self.cor_of_label.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.cor_of_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cor_of_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.cor_of_label.setObjectName("cor_of_label")
        self.horizontalLayout_8.addWidget(self.cor_of_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.cor_total_frames = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cor_total_frames.sizePolicy().hasHeightForWidth())
        self.cor_total_frames.setSizePolicy(sizePolicy)
        self.cor_total_frames.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.cor_total_frames.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.cor_total_frames.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.cor_total_frames.setObjectName("cor_total_frames")
        self.horizontalLayout_8.addWidget(self.cor_total_frames, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(2, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.voi_layout.addLayout(self.verticalLayout_7, 1, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(10, -1, 10, 20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cur_slice_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.cur_slice_label.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.cur_slice_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.cur_slice_label.setScaledContents(False)
        self.cur_slice_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cur_slice_label.setWordWrap(True)
        self.cur_slice_label.setObjectName("cur_slice_label")
        self.verticalLayout_2.addWidget(self.cur_slice_label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cur_slice_slider = QtWidgets.QSlider(parent=self.horizontalLayoutWidget_4)
        self.cur_slice_slider.setMinimumSize(QtCore.QSize(285, 0))
        self.cur_slice_slider.setMaximumSize(QtCore.QSize(285, 16777215))
        self.cur_slice_slider.setStyleSheet("QSlider {\n"
"    color: white;\n"
"}")
        self.cur_slice_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.cur_slice_slider.setObjectName("cur_slice_slider")
        self.horizontalLayout_5.addWidget(self.cur_slice_slider, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.cur_slice_spin_box = QtWidgets.QDoubleSpinBox(parent=self.horizontalLayoutWidget_4)
        self.cur_slice_spin_box.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cur_slice_spin_box.setStyleSheet("QDoubleSpinBox {\n"
"    background: white;\n"
"    color: black;\n"
"}")
        self.cur_slice_spin_box.setObjectName("cur_slice_spin_box")
        self.horizontalLayout_5.addWidget(self.cur_slice_spin_box, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.cur_slice_of_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.cur_slice_of_label.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.cur_slice_of_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cur_slice_of_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.cur_slice_of_label.setObjectName("cur_slice_of_label")
        self.horizontalLayout_5.addWidget(self.cur_slice_of_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.cur_slice_total = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.cur_slice_total.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.cur_slice_total.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.cur_slice_total.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.cur_slice_total.setObjectName("cur_slice_total")
        self.horizontalLayout_5.addWidget(self.cur_slice_total, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout_5.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.voiAlphaLayout_2 = QtWidgets.QVBoxLayout()
        self.voiAlphaLayout_2.setObjectName("voiAlphaLayout_2")
        self.alpha_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.alpha_label.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.alpha_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.alpha_label.setScaledContents(False)
        self.alpha_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.alpha_label.setWordWrap(True)
        self.alpha_label.setObjectName("alpha_label")
        self.voiAlphaLayout_2.addWidget(self.alpha_label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.alpha_status = QtWidgets.QProgressBar(parent=self.horizontalLayoutWidget_4)
        self.alpha_status.setMinimumSize(QtCore.QSize(285, 0))
        self.alpha_status.setMaximumSize(QtCore.QSize(285, 16777215))
        self.alpha_status.setProperty("value", 24)
        self.alpha_status.setObjectName("alpha_status")
        self.horizontalLayout_4.addWidget(self.alpha_status, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.alpha_spin_box = QtWidgets.QSpinBox(parent=self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.alpha_spin_box.setFont(font)
        self.alpha_spin_box.setStyleSheet("QSpinBox{\n"
"    background-color: white,\n"
"}")
        self.alpha_spin_box.setObjectName("alpha_spin_box")
        self.horizontalLayout_4.addWidget(self.alpha_spin_box, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.alpha_of_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.alpha_of_label.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.alpha_of_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.alpha_of_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.alpha_of_label.setObjectName("alpha_of_label")
        self.horizontalLayout_4.addWidget(self.alpha_of_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.alpha_total = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.alpha_total.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.alpha_total.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.alpha_total.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.alpha_total.setObjectName("alpha_total")
        self.horizontalLayout_4.addWidget(self.alpha_total, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.voiAlphaLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.voiAlphaLayout_2)
        self.construct_voi_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.construct_voi_label.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.construct_voi_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.construct_voi_label.setScaledContents(False)
        self.construct_voi_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.construct_voi_label.setWordWrap(True)
        self.construct_voi_label.setObjectName("construct_voi_label")
        self.verticalLayout_5.addWidget(self.construct_voi_label)
        self.drawVoiLayout_2 = QtWidgets.QGridLayout()
        self.drawVoiLayout_2.setObjectName("drawVoiLayout_2")
        self.undo_last_pt_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.undo_last_pt_button.setMinimumSize(QtCore.QSize(0, 36))
        self.undo_last_pt_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.undo_last_pt_button.setCheckable(False)
        self.undo_last_pt_button.setObjectName("undo_last_pt_button")
        self.drawVoiLayout_2.addWidget(self.undo_last_pt_button, 0, 1, 1, 1)
        self.interpolate_voi_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.interpolate_voi_button.setMinimumSize(QtCore.QSize(0, 36))
        self.interpolate_voi_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.interpolate_voi_button.setCheckable(False)
        self.interpolate_voi_button.setObjectName("interpolate_voi_button")
        self.drawVoiLayout_2.addWidget(self.interpolate_voi_button, 1, 1, 1, 1)
        self.draw_roi_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.draw_roi_button.setMinimumSize(QtCore.QSize(0, 36))
        self.draw_roi_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.draw_roi_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 16px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.draw_roi_button.setCheckable(True)
        self.draw_roi_button.setChecked(False)
        self.draw_roi_button.setObjectName("draw_roi_button")
        self.drawVoiLayout_2.addWidget(self.draw_roi_button, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.undo_last_roi_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.undo_last_roi_button.setMinimumSize(QtCore.QSize(0, 36))
        self.undo_last_roi_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.undo_last_roi_button.setCheckable(False)
        self.undo_last_roi_button.setObjectName("undo_last_roi_button")
        self.horizontalLayout.addWidget(self.undo_last_roi_button)
        self.close_roi_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.close_roi_button.setMinimumSize(QtCore.QSize(0, 36))
        self.close_roi_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.close_roi_button.setCheckable(False)
        self.close_roi_button.setObjectName("close_roi_button")
        self.horizontalLayout.addWidget(self.close_roi_button)
        self.drawVoiLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.drawVoiLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.restart_voi_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.restart_voi_button.setMinimumSize(QtCore.QSize(0, 36))
        self.restart_voi_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.restart_voi_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.restart_voi_button.setCheckable(False)
        self.restart_voi_button.setObjectName("restart_voi_button")
        self.horizontalLayout_2.addWidget(self.restart_voi_button)
        self.save_voi_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.save_voi_button.setMinimumSize(QtCore.QSize(0, 36))
        self.save_voi_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.save_voi_button.setCheckable(False)
        self.save_voi_button.setObjectName("save_voi_button")
        self.horizontalLayout_2.addWidget(self.save_voi_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.interp_loading_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.interp_loading_label.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: green;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.interp_loading_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.interp_loading_label.setScaledContents(False)
        self.interp_loading_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.interp_loading_label.setWordWrap(True)
        self.interp_loading_label.setObjectName("interp_loading_label")
        self.verticalLayout_5.addWidget(self.interp_loading_label)
        self.saving_voi_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.saving_voi_label.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: green;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.saving_voi_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.saving_voi_label.setScaledContents(False)
        self.saving_voi_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.saving_voi_label.setWordWrap(True)
        self.saving_voi_label.setObjectName("saving_voi_label")
        self.verticalLayout_5.addWidget(self.saving_voi_label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.save_folder_input = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_4)
        self.save_folder_input.setMinimumSize(QtCore.QSize(201, 31))
        self.save_folder_input.setMaximumSize(QtCore.QSize(401, 31))
        self.save_folder_input.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.save_folder_input.setObjectName("save_folder_input")
        self.gridLayout.addWidget(self.save_folder_input, 0, 1, 1, 1)
        self.dest_folder_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.dest_folder_label.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.dest_folder_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dest_folder_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.dest_folder_label.setObjectName("dest_folder_label")
        self.gridLayout.addWidget(self.dest_folder_label, 0, 0, 1, 1)
        self.chooseImageButtonsLayout_2 = QtWidgets.QHBoxLayout()
        self.chooseImageButtonsLayout_2.setSpacing(10)
        self.chooseImageButtonsLayout_2.setObjectName("chooseImageButtonsLayout_2")
        self.choose_save_folder_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.choose_save_folder_button.setMinimumSize(QtCore.QSize(131, 41))
        self.choose_save_folder_button.setMaximumSize(QtCore.QSize(131, 41))
        self.choose_save_folder_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.choose_save_folder_button.setObjectName("choose_save_folder_button")
        self.chooseImageButtonsLayout_2.addWidget(self.choose_save_folder_button)
        self.clear_save_folder_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.clear_save_folder_button.setMinimumSize(QtCore.QSize(131, 41))
        self.clear_save_folder_button.setMaximumSize(QtCore.QSize(131, 41))
        self.clear_save_folder_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clear_save_folder_button.setObjectName("clear_save_folder_button")
        self.chooseImageButtonsLayout_2.addWidget(self.clear_save_folder_button)
        self.gridLayout.addLayout(self.chooseImageButtonsLayout_2, 0, 2, 1, 1)
        self.voi_name_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.voi_name_label.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.voi_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.voi_name_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.voi_name_label.setObjectName("voi_name_label")
        self.gridLayout.addWidget(self.voi_name_label, 1, 0, 1, 1)
        self.save_name_input = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_4)
        self.save_name_input.setMinimumSize(QtCore.QSize(201, 31))
        self.save_name_input.setMaximumSize(QtCore.QSize(401, 31))
        self.save_name_input.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.save_name_input.setObjectName("save_name_input")
        self.gridLayout.addWidget(self.save_name_input, 1, 1, 1, 1)
        self.chooseImageButtonsLayout_4 = QtWidgets.QHBoxLayout()
        self.chooseImageButtonsLayout_4.setObjectName("chooseImageButtonsLayout_4")
        self.export_voi_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.export_voi_button.setMinimumSize(QtCore.QSize(131, 41))
        self.export_voi_button.setMaximumSize(QtCore.QSize(131, 41))
        self.export_voi_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.export_voi_button.setObjectName("export_voi_button")
        self.chooseImageButtonsLayout_4.addWidget(self.export_voi_button)
        self.back_from_save_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.back_from_save_button.setMinimumSize(QtCore.QSize(131, 41))
        self.back_from_save_button.setMaximumSize(QtCore.QSize(131, 41))
        self.back_from_save_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.back_from_save_button.setObjectName("back_from_save_button")
        self.chooseImageButtonsLayout_4.addWidget(self.back_from_save_button)
        self.gridLayout.addLayout(self.chooseImageButtonsLayout_4, 1, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.voi_layout.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.voi_layout.setColumnStretch(0, 1)
        self.voi_layout.setColumnStretch(1, 1)
        self.full_screen_layout.addLayout(self.voi_layout)

        self.retranslateUi(voi_drawer)
        QtCore.QMetaObject.connectSlotsByName(voi_drawer)

    def retranslateUi(self, voi_drawer):
        _translate = QtCore.QCoreApplication.translate
        voi_drawer.setWindowTitle(_translate("voi_drawer", "Draw Volume of Interest"))
        self.sidebar.setToolTip(_translate("voi_drawer", "<html><head/><body><p><br/></p></body></html>"))
        self.scanSelectionLabelSidebar_2.setText(_translate("voi_drawer", "Scan Selection:"))
        self.scanLabel_2.setText(_translate("voi_drawer", "Scan:"))
        self.scan_name_input.setText(_translate("voi_drawer", "Sample filename "))
        self.segSidebarLabel_2.setText(_translate("voi_drawer", "Segmentation Selection"))
        self.resultsLabel_2.setText(_translate("voi_drawer", "Results"))
        self.visualizationsLabel_2.setText(_translate("voi_drawer", "Visualizations"))
        self.analysisConfigLabel_2.setText(_translate("voi_drawer", "Analysis Configuration"))
        self.observing_label.setText(_translate("voi_drawer", "Observing!"))
        self.navigating_label.setText(_translate("voi_drawer", "Navigating!"))
        self.back_button.setText(_translate("voi_drawer", "Back"))
        self.toggle_crosshair_visibility_button.setText(_translate("voi_drawer", "Show/Hide Cross"))
        self.sag_plane_label.setText(_translate("voi_drawer", "Sagittal Plane"))
        self.sag_frame_num.setText(_translate("voi_drawer", "0"))
        self.sag_of_label.setText(_translate("voi_drawer", "of"))
        self.sag_total_frames.setText(_translate("voi_drawer", "0"))
        self.ax_plane_label.setText(_translate("voi_drawer", "Axial Plane"))
        self.ax_frame_num.setText(_translate("voi_drawer", "0"))
        self.ax_of_label.setText(_translate("voi_drawer", "of"))
        self.ax_total_frames.setText(_translate("voi_drawer", "0"))
        self.cor_plane_label.setText(_translate("voi_drawer", "Coronal Plane"))
        self.cor_frame_num.setText(_translate("voi_drawer", "0"))
        self.cor_of_label.setText(_translate("voi_drawer", "of"))
        self.cor_total_frames.setText(_translate("voi_drawer", "0"))
        self.cur_slice_label.setText(_translate("voi_drawer", "Current Slice (in seconds):"))
        self.cur_slice_of_label.setText(_translate("voi_drawer", "of"))
        self.cur_slice_total.setText(_translate("voi_drawer", "0"))
        self.alpha_label.setText(_translate("voi_drawer", "VOI Alpha:"))
        self.alpha_of_label.setText(_translate("voi_drawer", "of"))
        self.alpha_total.setText(_translate("voi_drawer", "255"))
        self.construct_voi_label.setText(_translate("voi_drawer", "Construct Volume of Interest (VOI):\n"
"For best results,  draw 1 ROI in each plane before interpolating"))
        self.undo_last_pt_button.setText(_translate("voi_drawer", "Undo Last Point"))
        self.interpolate_voi_button.setText(_translate("voi_drawer", "Interpolate VOI"))
        self.draw_roi_button.setText(_translate("voi_drawer", "Draw ROI"))
        self.undo_last_roi_button.setText(_translate("voi_drawer", "Undo Last ROI"))
        self.close_roi_button.setText(_translate("voi_drawer", "Close ROI"))
        self.restart_voi_button.setText(_translate("voi_drawer", "Restart VOI"))
        self.save_voi_button.setText(_translate("voi_drawer", "Save VOI"))
        self.interp_loading_label.setText(_translate("voi_drawer", "Interpolation Loading..."))
        self.saving_voi_label.setText(_translate("voi_drawer", "Saving VOI..."))
        self.dest_folder_label.setText(_translate("voi_drawer", "Dest Folder"))
        self.choose_save_folder_button.setText(_translate("voi_drawer", "Choose Folder"))
        self.clear_save_folder_button.setText(_translate("voi_drawer", "Clear Path"))
        self.voi_name_label.setText(_translate("voi_drawer", "VOI Name"))
        self.export_voi_button.setText(_translate("voi_drawer", "Save"))
        self.back_from_save_button.setText(_translate("voi_drawer", "Back"))
