# Form implementation generated from reading ui file 'src\ceus\seg_loading\ui\draw_roi.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_constructRoi(object):
    def setupUi(self, constructRoi):
        constructRoi.setObjectName("constructRoi")
        constructRoi.resize(1422, 725)
        constructRoi.setMinimumSize(QtCore.QSize(1400, 662))
        constructRoi.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.main_layout = QtWidgets.QVBoxLayout(constructRoi)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.full_screen_layout = QtWidgets.QHBoxLayout()
        self.full_screen_layout.setObjectName("full_screen_layout")
        self.side_bar_layout = QtWidgets.QVBoxLayout()
        self.side_bar_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.side_bar_layout.setSpacing(0)
        self.side_bar_layout.setObjectName("side_bar_layout")
        self.sidebar = QtWidgets.QWidget(parent=constructRoi)
        self.sidebar.setMinimumSize(QtCore.QSize(341, 601))
        self.sidebar.setMaximumSize(QtCore.QSize(241, 601))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.scanSelectionSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.scanSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.scanSelectionSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.scanSelectionSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.scanSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.scanSelectionSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.scanSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.scanSelectionSidebar.setObjectName("scanSelectionSidebar")
        self.scanSelectionLabelSidebar = QtWidgets.QLabel(parent=self.scanSelectionSidebar)
        self.scanSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.scanSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.scanSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scanSelectionLabelSidebar.setObjectName("scanSelectionLabelSidebar")
        self.scanLabel = QtWidgets.QLabel(parent=self.scanSelectionSidebar)
        self.scanLabel.setGeometry(QtCore.QRect(-60, 50, 191, 51))
        self.scanLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.scanLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scanLabel.setObjectName("scanLabel")
        self.scan_name_input = QtWidgets.QLabel(parent=self.scanSelectionSidebar)
        self.scan_name_input.setGeometry(QtCore.QRect(70, 50, 261, 51))
        self.scan_name_input.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.scan_name_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.scan_name_input.setObjectName("scan_name_input")
        self.segSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.segSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.segSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.segSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.segSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.segSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.segSidebar.setObjectName("segSidebar")
        self.segSidebarLabel = QtWidgets.QLabel(parent=self.segSidebar)
        self.segSidebarLabel.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.segSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.segSidebarLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.segSidebarLabel.setObjectName("segSidebarLabel")
        self.resultsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.resultsSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.resultsSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.resultsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.resultsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.resultsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.resultsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.resultsSidebar.setObjectName("resultsSidebar")
        self.resultsLabel = QtWidgets.QLabel(parent=self.resultsSidebar)
        self.resultsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.resultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.resultsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.resultsLabel.setObjectName("resultsLabel")
        self.visualizationsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.visualizationsSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.visualizationsSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.visualizationsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.visualizationsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.visualizationsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.visualizationsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.visualizationsSidebar.setObjectName("visualizationsSidebar")
        self.visualizationsLabel = QtWidgets.QLabel(parent=self.visualizationsSidebar)
        self.visualizationsLabel.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.visualizationsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.visualizationsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.visualizationsLabel.setObjectName("visualizationsLabel")
        self.analysisConfigSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.analysisConfigSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisConfigSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.analysisConfigSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisConfigSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.analysisConfigSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.analysisConfigSidebar.setObjectName("analysisConfigSidebar")
        self.analysisConfigLabel = QtWidgets.QLabel(parent=self.analysisConfigSidebar)
        self.analysisConfigLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisConfigLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisConfigLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.analysisConfigLabel.setObjectName("analysisConfigLabel")
        self.side_bar_layout.addWidget(self.sidebar)
        self.gridFrame_2 = QtWidgets.QFrame(parent=constructRoi)
        self.gridFrame_2.setMinimumSize(QtCore.QSize(341, 0))
        self.gridFrame_2.setMaximumSize(QtCore.QSize(341, 16777215))
        self.gridFrame_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.backButtonGrid_3 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.backButtonGrid_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.backButtonGrid_3.setContentsMargins(10, 10, 10, 10)
        self.backButtonGrid_3.setObjectName("backButtonGrid_3")
        self.back_button = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.back_button.setMinimumSize(QtCore.QSize(131, 41))
        self.back_button.setMaximumSize(QtCore.QSize(131, 41))
        self.back_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.backButtonGrid_3.addWidget(self.back_button, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.backButtonGrid_3.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.backButtonGrid_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.side_bar_layout.addWidget(self.gridFrame_2)
        self.full_screen_layout.addLayout(self.side_bar_layout)
        self.frame_preview_layout = QtWidgets.QVBoxLayout()
        self.frame_preview_layout.setContentsMargins(30, 10, 30, 10)
        self.frame_preview_layout.setSpacing(10)
        self.frame_preview_layout.setObjectName("frame_preview_layout")
        self.select_frame_label = QtWidgets.QLabel(parent=constructRoi)
        self.select_frame_label.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.select_frame_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.select_frame_label.setScaledContents(False)
        self.select_frame_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.select_frame_label.setWordWrap(True)
        self.select_frame_label.setObjectName("select_frame_label")
        self.frame_preview_layout.addWidget(self.select_frame_label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.back_from_drag_button = QtWidgets.QPushButton(parent=constructRoi)
        self.back_from_drag_button.setMinimumSize(QtCore.QSize(241, 41))
        self.back_from_drag_button.setMaximumSize(QtCore.QSize(241, 41))
        self.back_from_drag_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.back_from_drag_button.setCheckable(True)
        self.back_from_drag_button.setChecked(False)
        self.back_from_drag_button.setObjectName("back_from_drag_button")
        self.horizontalLayout_4.addWidget(self.back_from_drag_button)
        self.save_drag_button = QtWidgets.QPushButton(parent=constructRoi)
        self.save_drag_button.setMinimumSize(QtCore.QSize(241, 41))
        self.save_drag_button.setMaximumSize(QtCore.QSize(241, 41))
        self.save_drag_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.save_drag_button.setCheckable(True)
        self.save_drag_button.setChecked(False)
        self.save_drag_button.setObjectName("save_drag_button")
        self.horizontalLayout_4.addWidget(self.save_drag_button)
        self.frame_preview_layout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.draw_pts_type_button = QtWidgets.QPushButton(parent=constructRoi)
        self.draw_pts_type_button.setMinimumSize(QtCore.QSize(221, 41))
        self.draw_pts_type_button.setMaximumSize(QtCore.QSize(221, 41))
        self.draw_pts_type_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.draw_pts_type_button.setCheckable(True)
        self.draw_pts_type_button.setChecked(False)
        self.draw_pts_type_button.setObjectName("draw_pts_type_button")
        self.horizontalLayout.addWidget(self.draw_pts_type_button)
        self.draw_freehand_drag_type_button = QtWidgets.QPushButton(parent=constructRoi)
        self.draw_freehand_drag_type_button.setMinimumSize(QtCore.QSize(241, 41))
        self.draw_freehand_drag_type_button.setMaximumSize(QtCore.QSize(241, 41))
        self.draw_freehand_drag_type_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 16px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.draw_freehand_drag_type_button.setCheckable(False)
        self.draw_freehand_drag_type_button.setChecked(False)
        self.draw_freehand_drag_type_button.setObjectName("draw_freehand_drag_type_button")
        self.horizontalLayout.addWidget(self.draw_freehand_drag_type_button)
        self.draw_rect_drag_type_button = QtWidgets.QPushButton(parent=constructRoi)
        self.draw_rect_drag_type_button.setMinimumSize(QtCore.QSize(241, 41))
        self.draw_rect_drag_type_button.setMaximumSize(QtCore.QSize(241, 41))
        self.draw_rect_drag_type_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 16px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.draw_rect_drag_type_button.setCheckable(False)
        self.draw_rect_drag_type_button.setChecked(False)
        self.draw_rect_drag_type_button.setObjectName("draw_rect_drag_type_button")
        self.horizontalLayout.addWidget(self.draw_rect_drag_type_button)
        self.frame_preview_layout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clear_roi_button = QtWidgets.QPushButton(parent=constructRoi)
        self.clear_roi_button.setMinimumSize(QtCore.QSize(141, 41))
        self.clear_roi_button.setMaximumSize(QtCore.QSize(141, 41))
        self.clear_roi_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clear_roi_button.setCheckable(False)
        self.clear_roi_button.setObjectName("clear_roi_button")
        self.horizontalLayout_3.addWidget(self.clear_roi_button)
        self.undo_last_pt_button = QtWidgets.QPushButton(parent=constructRoi)
        self.undo_last_pt_button.setMinimumSize(QtCore.QSize(141, 41))
        self.undo_last_pt_button.setMaximumSize(QtCore.QSize(141, 41))
        self.undo_last_pt_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.undo_last_pt_button.setCheckable(False)
        self.undo_last_pt_button.setObjectName("undo_last_pt_button")
        self.horizontalLayout_3.addWidget(self.undo_last_pt_button)
        self.close_roi_button = QtWidgets.QPushButton(parent=constructRoi)
        self.close_roi_button.setMinimumSize(QtCore.QSize(141, 41))
        self.close_roi_button.setMaximumSize(QtCore.QSize(141, 41))
        self.close_roi_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.close_roi_button.setCheckable(False)
        self.close_roi_button.setObjectName("close_roi_button")
        self.horizontalLayout_3.addWidget(self.close_roi_button)
        self.back_from_pts_button = QtWidgets.QPushButton(parent=constructRoi)
        self.back_from_pts_button.setMinimumSize(QtCore.QSize(141, 41))
        self.back_from_pts_button.setMaximumSize(QtCore.QSize(141, 41))
        self.back_from_pts_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.back_from_pts_button.setCheckable(False)
        self.back_from_pts_button.setObjectName("back_from_pts_button")
        self.horizontalLayout_3.addWidget(self.back_from_pts_button)
        self.save_pts_button = QtWidgets.QPushButton(parent=constructRoi)
        self.save_pts_button.setMinimumSize(QtCore.QSize(141, 41))
        self.save_pts_button.setMaximumSize(QtCore.QSize(141, 41))
        self.save_pts_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.save_pts_button.setCheckable(False)
        self.save_pts_button.setObjectName("save_pts_button")
        self.horizontalLayout_3.addWidget(self.save_pts_button)
        self.frame_preview_layout.addLayout(self.horizontalLayout_3)
        self.save_roi_layout = QtWidgets.QGridLayout()
        self.save_roi_layout.setContentsMargins(-1, -1, -1, 10)
        self.save_roi_layout.setSpacing(10)
        self.save_roi_layout.setObjectName("save_roi_layout")
        self.save_folder_input = QtWidgets.QLineEdit(parent=constructRoi)
        self.save_folder_input.setMinimumSize(QtCore.QSize(201, 31))
        self.save_folder_input.setMaximumSize(QtCore.QSize(401, 31))
        self.save_folder_input.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.save_folder_input.setObjectName("save_folder_input")
        self.save_roi_layout.addWidget(self.save_folder_input, 0, 1, 1, 1)
        self.dest_folder_label = QtWidgets.QLabel(parent=constructRoi)
        self.dest_folder_label.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.dest_folder_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dest_folder_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.dest_folder_label.setObjectName("dest_folder_label")
        self.save_roi_layout.addWidget(self.dest_folder_label, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.roi_name_label = QtWidgets.QLabel(parent=constructRoi)
        self.roi_name_label.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.roi_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.roi_name_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.roi_name_label.setObjectName("roi_name_label")
        self.save_roi_layout.addWidget(self.roi_name_label, 2, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.save_name_input = QtWidgets.QLineEdit(parent=constructRoi)
        self.save_name_input.setMinimumSize(QtCore.QSize(201, 31))
        self.save_name_input.setMaximumSize(QtCore.QSize(401, 31))
        self.save_name_input.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.save_name_input.setObjectName("save_name_input")
        self.save_roi_layout.addWidget(self.save_name_input, 2, 1, 1, 1)
        self.chooseImageButtonsLayout_2 = QtWidgets.QHBoxLayout()
        self.chooseImageButtonsLayout_2.setSpacing(10)
        self.chooseImageButtonsLayout_2.setObjectName("chooseImageButtonsLayout_2")
        self.choose_save_folder_button = QtWidgets.QPushButton(parent=constructRoi)
        self.choose_save_folder_button.setMinimumSize(QtCore.QSize(131, 41))
        self.choose_save_folder_button.setMaximumSize(QtCore.QSize(131, 41))
        self.choose_save_folder_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.choose_save_folder_button.setObjectName("choose_save_folder_button")
        self.chooseImageButtonsLayout_2.addWidget(self.choose_save_folder_button)
        self.clear_save_folder_button = QtWidgets.QPushButton(parent=constructRoi)
        self.clear_save_folder_button.setMinimumSize(QtCore.QSize(131, 41))
        self.clear_save_folder_button.setMaximumSize(QtCore.QSize(131, 41))
        self.clear_save_folder_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clear_save_folder_button.setObjectName("clear_save_folder_button")
        self.chooseImageButtonsLayout_2.addWidget(self.clear_save_folder_button)
        self.save_roi_layout.addLayout(self.chooseImageButtonsLayout_2, 0, 2, 1, 1)
        self.chooseImageButtonsLayout_4 = QtWidgets.QHBoxLayout()
        self.chooseImageButtonsLayout_4.setObjectName("chooseImageButtonsLayout_4")
        self.save_roi_button = QtWidgets.QPushButton(parent=constructRoi)
        self.save_roi_button.setMinimumSize(QtCore.QSize(131, 41))
        self.save_roi_button.setMaximumSize(QtCore.QSize(131, 41))
        self.save_roi_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.save_roi_button.setObjectName("save_roi_button")
        self.chooseImageButtonsLayout_4.addWidget(self.save_roi_button)
        self.back_from_save_button = QtWidgets.QPushButton(parent=constructRoi)
        self.back_from_save_button.setMinimumSize(QtCore.QSize(131, 41))
        self.back_from_save_button.setMaximumSize(QtCore.QSize(131, 41))
        self.back_from_save_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.back_from_save_button.setObjectName("back_from_save_button")
        self.chooseImageButtonsLayout_4.addWidget(self.back_from_save_button)
        self.save_roi_layout.addLayout(self.chooseImageButtonsLayout_4, 2, 2, 1, 1)
        self.save_roi_layout.setColumnStretch(0, 1)
        self.save_roi_layout.setColumnStretch(1, 10)
        self.save_roi_layout.setColumnStretch(2, 10)
        self.save_roi_layout.setRowStretch(0, 1)
        self.save_roi_layout.setRowStretch(1, 10)
        self.save_roi_layout.setRowStretch(2, 10)
        self.frame_preview_layout.addLayout(self.save_roi_layout)
        self.im_display_frame = QtWidgets.QFrame(parent=constructRoi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.im_display_frame.sizePolicy().hasHeightForWidth())
        self.im_display_frame.setSizePolicy(sizePolicy)
        self.im_display_frame.setMinimumSize(QtCore.QSize(501, 321))
        self.im_display_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.im_display_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.im_display_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.im_display_frame.setObjectName("im_display_frame")
        self.frame_preview_layout.addWidget(self.im_display_frame)
        self.frameControlsLayout = QtWidgets.QHBoxLayout()
        self.frameControlsLayout.setSpacing(10)
        self.frameControlsLayout.setObjectName("frameControlsLayout")
        self.frame_slider = QtWidgets.QSlider(parent=constructRoi)
        self.frame_slider.setMinimumSize(QtCore.QSize(251, 41))
        self.frame_slider.setMaximumSize(QtCore.QSize(251, 41))
        self.frame_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.frameControlsLayout.addWidget(self.frame_slider)
        self.cur_frame_label = QtWidgets.QLabel(parent=constructRoi)
        self.cur_frame_label.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.cur_frame_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.cur_frame_label.setScaledContents(False)
        self.cur_frame_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.cur_frame_label.setWordWrap(True)
        self.cur_frame_label.setObjectName("cur_frame_label")
        self.frameControlsLayout.addWidget(self.cur_frame_label)
        self.of_frames_label = QtWidgets.QLabel(parent=constructRoi)
        self.of_frames_label.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.of_frames_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.of_frames_label.setScaledContents(False)
        self.of_frames_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.of_frames_label.setWordWrap(True)
        self.of_frames_label.setObjectName("of_frames_label")
        self.frameControlsLayout.addWidget(self.of_frames_label)
        self.total_frames_label = QtWidgets.QLabel(parent=constructRoi)
        self.total_frames_label.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.total_frames_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.total_frames_label.setScaledContents(False)
        self.total_frames_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.total_frames_label.setWordWrap(True)
        self.total_frames_label.setObjectName("total_frames_label")
        self.frameControlsLayout.addWidget(self.total_frames_label)
        self.seconds_label = QtWidgets.QLabel(parent=constructRoi)
        self.seconds_label.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.seconds_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.seconds_label.setScaledContents(False)
        self.seconds_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.seconds_label.setWordWrap(True)
        self.seconds_label.setObjectName("seconds_label")
        self.frameControlsLayout.addWidget(self.seconds_label)
        self.frame_preview_layout.addLayout(self.frameControlsLayout)
        self.frame_preview_layout.setStretch(0, 1)
        self.frame_preview_layout.setStretch(6, 1)
        self.full_screen_layout.addLayout(self.frame_preview_layout)
        self.main_layout.addLayout(self.full_screen_layout)

        self.retranslateUi(constructRoi)
        QtCore.QMetaObject.connectSlotsByName(constructRoi)

    def retranslateUi(self, constructRoi):
        _translate = QtCore.QCoreApplication.translate
        constructRoi.setWindowTitle(_translate("constructRoi", "Select Region of Interest"))
        self.sidebar.setToolTip(_translate("constructRoi", "<html><head/><body><p><br/></p></body></html>"))
        self.scanSelectionLabelSidebar.setText(_translate("constructRoi", "Scan Selection:"))
        self.scanLabel.setText(_translate("constructRoi", "Scan:"))
        self.scan_name_input.setText(_translate("constructRoi", "Sample filename "))
        self.segSidebarLabel.setText(_translate("constructRoi", "Segmentation Selection"))
        self.resultsLabel.setText(_translate("constructRoi", "Results"))
        self.visualizationsLabel.setText(_translate("constructRoi", "Visualizations"))
        self.analysisConfigLabel.setText(_translate("constructRoi", "Analysis Configuration"))
        self.back_button.setText(_translate("constructRoi", "Back"))
        self.select_frame_label.setText(_translate("constructRoi", "Select Frame to Segment:"))
        self.back_from_drag_button.setText(_translate("constructRoi", "Back"))
        self.save_drag_button.setText(_translate("constructRoi", "Save ROI"))
        self.draw_pts_type_button.setText(_translate("constructRoi", "Draw Freehand w Points"))
        self.draw_freehand_drag_type_button.setText(_translate("constructRoi", "Draw Freehand by Dragging"))
        self.draw_rect_drag_type_button.setText(_translate("constructRoi", "Draw Rectangle by Dragging"))
        self.clear_roi_button.setText(_translate("constructRoi", "Clear ROI"))
        self.undo_last_pt_button.setText(_translate("constructRoi", "Undo Last Point"))
        self.close_roi_button.setText(_translate("constructRoi", "Close ROI"))
        self.back_from_pts_button.setText(_translate("constructRoi", "Back"))
        self.save_pts_button.setText(_translate("constructRoi", "Save ROI"))
        self.dest_folder_label.setText(_translate("constructRoi", "Dest Folder"))
        self.roi_name_label.setText(_translate("constructRoi", "ROI Name"))
        self.choose_save_folder_button.setText(_translate("constructRoi", "Choose Folder"))
        self.clear_save_folder_button.setText(_translate("constructRoi", "Clear Path"))
        self.save_roi_button.setText(_translate("constructRoi", "Save"))
        self.back_from_save_button.setText(_translate("constructRoi", "Back"))
        self.cur_frame_label.setText(_translate("constructRoi", "0"))
        self.of_frames_label.setText(_translate("constructRoi", "of"))
        self.total_frames_label.setText(_translate("constructRoi", "0"))
        self.seconds_label.setText(_translate("constructRoi", "seconds"))
