# Form implementation generated from reading ui file 'D:\Omid\0_main\05.01.2026\5_QuantUS-OpenSource\QuantUS\src\ceus\seg_loading\ui\seg_file_selection.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_seg_file_selector(object):
    def setupUi(self, seg_file_selector):
        seg_file_selector.setObjectName("seg_file_selector")
        seg_file_selector.resize(1512, 829)
        seg_file_selector.setMinimumSize(QtCore.QSize(0, 0))
        seg_file_selector.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=seg_file_selector)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(70, 30, 1198, 751))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.full_screen_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.full_screen_layout.setContentsMargins(0, 0, 0, 0)
        self.full_screen_layout.setObjectName("full_screen_layout")
        self.side_bar_layout = QtWidgets.QVBoxLayout()
        self.side_bar_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.side_bar_layout.setSpacing(0)
        self.side_bar_layout.setObjectName("side_bar_layout")
        self.sidebar_2 = QtWidgets.QWidget(parent=self.horizontalLayoutWidget_4)
        self.sidebar_2.setMinimumSize(QtCore.QSize(341, 601))
        self.sidebar_2.setMaximumSize(QtCore.QSize(241, 601))
        self.sidebar_2.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar_2.setObjectName("sidebar_2")
        self.scanSelectionSidebar = QtWidgets.QFrame(parent=self.sidebar_2)
        self.scanSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.scanSelectionSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.scanSelectionSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.scanSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.scanSelectionSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.scanSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.scanSelectionSidebar.setObjectName("scanSelectionSidebar")
        self.scanSelectionLabelSidebar = QtWidgets.QLabel(parent=self.scanSelectionSidebar)
        self.scanSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.scanSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.scanSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scanSelectionLabelSidebar.setObjectName("scanSelectionLabelSidebar")
        self.scanLabel = QtWidgets.QLabel(parent=self.scanSelectionSidebar)
        self.scanLabel.setGeometry(QtCore.QRect(-60, 50, 191, 51))
        self.scanLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.scanLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scanLabel.setObjectName("scanLabel")
        self.image_path_input = QtWidgets.QLabel(parent=self.scanSelectionSidebar)
        self.image_path_input.setGeometry(QtCore.QRect(70, 50, 261, 51))
        self.image_path_input.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.image_path_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.image_path_input.setObjectName("image_path_input")
        self.segSidebar = QtWidgets.QFrame(parent=self.sidebar_2)
        self.segSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.segSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.segSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.segSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.segSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.segSidebar.setObjectName("segSidebar")
        self.segSidebarLabel = QtWidgets.QLabel(parent=self.segSidebar)
        self.segSidebarLabel.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.segSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.segSidebarLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.segSidebarLabel.setObjectName("segSidebarLabel")
        self.resultsSidebar = QtWidgets.QFrame(parent=self.sidebar_2)
        self.resultsSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.resultsSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.resultsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.resultsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.resultsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.resultsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.resultsSidebar.setObjectName("resultsSidebar")
        self.resultsLabel = QtWidgets.QLabel(parent=self.resultsSidebar)
        self.resultsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.resultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.resultsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.resultsLabel.setObjectName("resultsLabel")
        self.visualizationsSidebar = QtWidgets.QFrame(parent=self.sidebar_2)
        self.visualizationsSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.visualizationsSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.visualizationsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.visualizationsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.visualizationsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.visualizationsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.visualizationsSidebar.setObjectName("visualizationsSidebar")
        self.visualizationsLabel = QtWidgets.QLabel(parent=self.visualizationsSidebar)
        self.visualizationsLabel.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.visualizationsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.visualizationsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.visualizationsLabel.setObjectName("visualizationsLabel")
        self.analysisConfigSidebar = QtWidgets.QFrame(parent=self.sidebar_2)
        self.analysisConfigSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisConfigSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.analysisConfigSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisConfigSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.analysisConfigSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.analysisConfigSidebar.setObjectName("analysisConfigSidebar")
        self.analysisConfigLabel = QtWidgets.QLabel(parent=self.analysisConfigSidebar)
        self.analysisConfigLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisConfigLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisConfigLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.analysisConfigLabel.setObjectName("analysisConfigLabel")
        self.side_bar_layout.addWidget(self.sidebar_2)
        self.gridFrame_2 = QtWidgets.QFrame(parent=self.horizontalLayoutWidget_4)
        self.gridFrame_2.setMinimumSize(QtCore.QSize(341, 0))
        self.gridFrame_2.setMaximumSize(QtCore.QSize(341, 16777215))
        self.gridFrame_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.backButtonGrid_3 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.backButtonGrid_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.backButtonGrid_3.setContentsMargins(10, 10, 10, 10)
        self.backButtonGrid_3.setObjectName("backButtonGrid_3")
        self.back_button = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.back_button.setMinimumSize(QtCore.QSize(131, 41))
        self.back_button.setMaximumSize(QtCore.QSize(131, 41))
        self.back_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.backButtonGrid_3.addWidget(self.back_button, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.backButtonGrid_3.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.backButtonGrid_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.side_bar_layout.addWidget(self.gridFrame_2)
        self.full_screen_layout.addLayout(self.side_bar_layout)
        self.seg_loading_layout = QtWidgets.QVBoxLayout()
        self.seg_loading_layout.setContentsMargins(30, 30, 30, 30)
        self.seg_loading_layout.setSpacing(20)
        self.seg_loading_layout.setObjectName("seg_loading_layout")
        self.select_seg_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.select_seg_label.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.select_seg_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.select_seg_label.setScaledContents(False)
        self.select_seg_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.select_seg_label.setWordWrap(True)
        self.select_seg_label.setObjectName("select_seg_label")
        self.seg_loading_layout.addWidget(self.select_seg_label)
        self.chooseImgLayout = QtWidgets.QVBoxLayout()
        self.chooseImgLayout.setContentsMargins(20, -1, 20, -1)
        self.chooseImgLayout.setObjectName("chooseImgLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.chooseImgLayout.addItem(spacerItem2)
        self.seg_path_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.seg_path_label.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.seg_path_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.seg_path_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.seg_path_label.setObjectName("seg_path_label")
        self.chooseImgLayout.addWidget(self.seg_path_label)
        self.seg_path_input = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_4)
        self.seg_path_input.setMinimumSize(QtCore.QSize(201, 31))
        self.seg_path_input.setMaximumSize(QtCore.QSize(401, 31))
        self.seg_path_input.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.seg_path_input.setObjectName("seg_path_input")
        self.chooseImgLayout.addWidget(self.seg_path_input, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.chooseImageButtonsLayout = QtWidgets.QHBoxLayout()
        self.chooseImageButtonsLayout.setSpacing(1)
        self.chooseImageButtonsLayout.setObjectName("chooseImageButtonsLayout")
        self.choose_seg_path_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.choose_seg_path_button.setMinimumSize(QtCore.QSize(131, 41))
        self.choose_seg_path_button.setMaximumSize(QtCore.QSize(131, 41))
        self.choose_seg_path_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.choose_seg_path_button.setObjectName("choose_seg_path_button")
        self.chooseImageButtonsLayout.addWidget(self.choose_seg_path_button, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.clear_seg_path_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.clear_seg_path_button.setMinimumSize(QtCore.QSize(131, 41))
        self.clear_seg_path_button.setMaximumSize(QtCore.QSize(131, 41))
        self.clear_seg_path_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clear_seg_path_button.setObjectName("clear_seg_path_button")
        self.chooseImageButtonsLayout.addWidget(self.clear_seg_path_button, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.chooseImgLayout.addLayout(self.chooseImageButtonsLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.chooseImgLayout.addItem(spacerItem3)
        self.seg_loading_layout.addLayout(self.chooseImgLayout)
        self.loading_options_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.loading_options_label.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.loading_options_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.loading_options_label.setScaledContents(False)
        self.loading_options_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loading_options_label.setWordWrap(True)
        self.loading_options_label.setObjectName("loading_options_label")
        self.seg_loading_layout.addWidget(self.loading_options_label)
        self.loading_options_table = QtWidgets.QTableWidget(parent=self.horizontalLayoutWidget_4)
        self.loading_options_table.setStyleSheet("QTableWidget {\n"
"    background: rgb(108, 108, 108);\n"
"    color: white;\n"
"}")
        self.loading_options_table.setDragEnabled(False)
        self.loading_options_table.setRowCount(0)
        self.loading_options_table.setColumnCount(0)
        self.loading_options_table.setObjectName("loading_options_table")
        self.loading_options_table.horizontalHeader().setCascadingSectionResizes(False)
        self.seg_loading_layout.addWidget(self.loading_options_table)
        self.accept_seg_path_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.accept_seg_path_button.setMinimumSize(QtCore.QSize(131, 41))
        self.accept_seg_path_button.setMaximumSize(QtCore.QSize(131, 41))
        self.accept_seg_path_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.accept_seg_path_button.setObjectName("accept_seg_path_button")
        self.seg_loading_layout.addWidget(self.accept_seg_path_button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.loading_screen_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.loading_screen_label.setStyleSheet("QLabel {\n"
"    color: rgb(0, 255, 0);\n"
"    font-size: 20px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.loading_screen_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loading_screen_label.setObjectName("loading_screen_label")
        self.seg_loading_layout.addWidget(self.loading_screen_label)
        self.select_seg_error_msg = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.select_seg_error_msg.setStyleSheet("QLabel {\n"
"    color: rgb(255, 0, 23);\n"
"    font-size: 20px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.select_seg_error_msg.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.select_seg_error_msg.setObjectName("select_seg_error_msg")
        self.seg_loading_layout.addWidget(self.select_seg_error_msg)
        self.seg_loading_layout.setStretch(0, 2)
        self.seg_loading_layout.setStretch(4, 3)
        self.seg_loading_layout.setStretch(6, 2)
        self.full_screen_layout.addLayout(self.seg_loading_layout)

        self.retranslateUi(seg_file_selector)
        QtCore.QMetaObject.connectSlotsByName(seg_file_selector)

    def retranslateUi(self, seg_file_selector):
        _translate = QtCore.QCoreApplication.translate
        seg_file_selector.setWindowTitle(_translate("seg_file_selector", "Select Segmentation File"))
        self.sidebar_2.setToolTip(_translate("seg_file_selector", "<html><head/><body><p><br/></p></body></html>"))
        self.scanSelectionLabelSidebar.setText(_translate("seg_file_selector", "Scan Selection:"))
        self.scanLabel.setText(_translate("seg_file_selector", "Scan:"))
        self.image_path_input.setText(_translate("seg_file_selector", "Sample filename "))
        self.segSidebarLabel.setText(_translate("seg_file_selector", "Segmentation Selection"))
        self.resultsLabel.setText(_translate("seg_file_selector", "Results"))
        self.visualizationsLabel.setText(_translate("seg_file_selector", "Visualizations"))
        self.analysisConfigLabel.setText(_translate("seg_file_selector", "Analysis Configuration"))
        self.back_button.setText(_translate("seg_file_selector", "Back"))
        self.select_seg_label.setText(_translate("seg_file_selector", "Select Segmentation File to Load:"))
        self.seg_path_label.setText(_translate("seg_file_selector", "Input Path to Image file\n"
" (.rf, .rfd, .mat, .bin)"))
        self.choose_seg_path_button.setText(_translate("seg_file_selector", "Choose File"))
        self.clear_seg_path_button.setText(_translate("seg_file_selector", "Clear Path"))
        self.loading_options_label.setText(_translate("seg_file_selector", "\n"
"Segmentation Loading Options:"))
        self.loading_options_table.setSortingEnabled(False)
        self.accept_seg_path_button.setText(_translate("seg_file_selector", "Accept"))
        self.loading_screen_label.setText(_translate("seg_file_selector", "LOADING...."))
        self.select_seg_error_msg.setText(_translate("seg_file_selector", "ERROR: At least one dimension of phantom data\n"
"smaller than corresponding dimension\n"
"of image data"))
