# Form implementation generated from reading ui file 'D:\Omid\0_main\05.01.2026\5_QuantUS-OpenSource\QuantUS\src\ceus\seg_loading\ui\seg_type_selection.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_seg_type_selector(object):
    def setupUi(self, seg_type_selector):
        seg_type_selector.setObjectName("seg_type_selector")
        seg_type_selector.resize(1287, 806)
        seg_type_selector.setMinimumSize(QtCore.QSize(0, 0))
        seg_type_selector.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=seg_type_selector)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 1281, 801))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.full_screen_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.full_screen_layout.setContentsMargins(0, 0, 0, 0)
        self.full_screen_layout.setObjectName("full_screen_layout")
        self.side_bar_layout = QtWidgets.QVBoxLayout()
        self.side_bar_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.side_bar_layout.setSpacing(0)
        self.side_bar_layout.setObjectName("side_bar_layout")
        self.sidebar = QtWidgets.QWidget(parent=self.horizontalLayoutWidget_4)
        self.sidebar.setMinimumSize(QtCore.QSize(341, 601))
        self.sidebar.setMaximumSize(QtCore.QSize(241, 601))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.scanSelectionSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.scanSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.scanSelectionSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.scanSelectionSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.scanSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.scanSelectionSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.scanSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.scanSelectionSidebar.setObjectName("scanSelectionSidebar")
        self.scanSelectionLabelSidebar = QtWidgets.QLabel(parent=self.scanSelectionSidebar)
        self.scanSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.scanSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.scanSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scanSelectionLabelSidebar.setObjectName("scanSelectionLabelSidebar")
        self.scanLabel = QtWidgets.QLabel(parent=self.scanSelectionSidebar)
        self.scanLabel.setGeometry(QtCore.QRect(-60, 50, 191, 51))
        self.scanLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.scanLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scanLabel.setObjectName("scanLabel")
        self.scan_name_input = QtWidgets.QLabel(parent=self.scanSelectionSidebar)
        self.scan_name_input.setGeometry(QtCore.QRect(70, 50, 261, 51))
        self.scan_name_input.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.scan_name_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.scan_name_input.setObjectName("scan_name_input")
        self.segSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.segSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.segSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.segSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.segSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.segSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.segSidebar.setObjectName("segSidebar")
        self.segSidebarLabel = QtWidgets.QLabel(parent=self.segSidebar)
        self.segSidebarLabel.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.segSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.segSidebarLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.segSidebarLabel.setObjectName("segSidebarLabel")
        self.resultsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.resultsSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.resultsSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.resultsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.resultsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.resultsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.resultsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.resultsSidebar.setObjectName("resultsSidebar")
        self.resultsLabel = QtWidgets.QLabel(parent=self.resultsSidebar)
        self.resultsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.resultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.resultsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.resultsLabel.setObjectName("resultsLabel")
        self.visualizationsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.visualizationsSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.visualizationsSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.visualizationsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.visualizationsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.visualizationsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.visualizationsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.visualizationsSidebar.setObjectName("visualizationsSidebar")
        self.visualizationsLabel = QtWidgets.QLabel(parent=self.visualizationsSidebar)
        self.visualizationsLabel.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.visualizationsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.visualizationsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.visualizationsLabel.setObjectName("visualizationsLabel")
        self.analysisConfigSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.analysisConfigSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisConfigSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.analysisConfigSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisConfigSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.analysisConfigSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.analysisConfigSidebar.setObjectName("analysisConfigSidebar")
        self.analysisConfigLabel = QtWidgets.QLabel(parent=self.analysisConfigSidebar)
        self.analysisConfigLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisConfigLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisConfigLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.analysisConfigLabel.setObjectName("analysisConfigLabel")
        self.side_bar_layout.addWidget(self.sidebar)
        self.gridFrame_2 = QtWidgets.QFrame(parent=self.horizontalLayoutWidget_4)
        self.gridFrame_2.setMinimumSize(QtCore.QSize(341, 0))
        self.gridFrame_2.setMaximumSize(QtCore.QSize(341, 16777215))
        self.gridFrame_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.backButtonGrid_3 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.backButtonGrid_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.backButtonGrid_3.setContentsMargins(10, 10, 10, 10)
        self.backButtonGrid_3.setObjectName("backButtonGrid_3")
        self.back_button = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.back_button.setMinimumSize(QtCore.QSize(131, 41))
        self.back_button.setMaximumSize(QtCore.QSize(131, 41))
        self.back_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.backButtonGrid_3.addWidget(self.back_button, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.backButtonGrid_3.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.backButtonGrid_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.side_bar_layout.addWidget(self.gridFrame_2)
        self.full_screen_layout.addLayout(self.side_bar_layout)
        self.select_type_layout = QtWidgets.QVBoxLayout()
        self.select_type_layout.setContentsMargins(30, -1, 30, -1)
        self.select_type_layout.setSpacing(50)
        self.select_type_layout.setObjectName("select_type_layout")
        self.select_type_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.select_type_label.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.select_type_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.select_type_label.setScaledContents(False)
        self.select_type_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.select_type_label.setWordWrap(True)
        self.select_type_label.setObjectName("select_type_label")
        self.select_type_layout.addWidget(self.select_type_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.seg_type_dropdown = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_4)
        self.seg_type_dropdown.setMinimumSize(QtCore.QSize(180, 41))
        self.seg_type_dropdown.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.seg_type_dropdown.setFont(font)
        self.seg_type_dropdown.setStyleSheet("QComboBox {\n"
"    color: white;\n"
"}")
        self.seg_type_dropdown.setObjectName("seg_type_dropdown")
        self.select_type_layout.addWidget(self.seg_type_dropdown)
        self.accept_type_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.accept_type_button.setMinimumSize(QtCore.QSize(131, 41))
        self.accept_type_button.setMaximumSize(QtCore.QSize(131, 41))
        self.accept_type_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.accept_type_button.setObjectName("accept_type_button")
        self.select_type_layout.addWidget(self.accept_type_button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.select_type_layout.addItem(spacerItem2)
        self.select_type_layout.setStretch(0, 2)
        self.select_type_layout.setStretch(1, 2)
        self.select_type_layout.setStretch(2, 2)
        self.select_type_layout.setStretch(3, 1)
        self.full_screen_layout.addLayout(self.select_type_layout)

        self.retranslateUi(seg_type_selector)
        QtCore.QMetaObject.connectSlotsByName(seg_type_selector)

    def retranslateUi(self, seg_type_selector):
        _translate = QtCore.QCoreApplication.translate
        seg_type_selector.setWindowTitle(_translate("seg_type_selector", "Select Segmentation Type"))
        self.sidebar.setToolTip(_translate("seg_type_selector", "<html><head/><body><p><br/></p></body></html>"))
        self.scanSelectionLabelSidebar.setText(_translate("seg_type_selector", "Scan Selection:"))
        self.scanLabel.setText(_translate("seg_type_selector", "Scan:"))
        self.scan_name_input.setText(_translate("seg_type_selector", "Sample filename "))
        self.segSidebarLabel.setText(_translate("seg_type_selector", "Segmentation Selection"))
        self.resultsLabel.setText(_translate("seg_type_selector", "Results"))
        self.visualizationsLabel.setText(_translate("seg_type_selector", "Visualizations"))
        self.analysisConfigLabel.setText(_translate("seg_type_selector", "Analysis Configuration"))
        self.back_button.setText(_translate("seg_type_selector", "Back"))
        self.select_type_label.setText(_translate("seg_type_selector", "Select Segmentation Type:"))
        self.accept_type_button.setText(_translate("seg_type_selector", "Accept"))
