# Form implementation generated from reading ui file 'D:\Omid\0_main\05.01.2026\5_QuantUS-OpenSource\QuantUS\src\qus\image_loading\ui\file_selection.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_selectImage(object):
    def setupUi(self, selectImage):
        selectImage.setObjectName("selectImage")
        selectImage.resize(1418, 832)
        selectImage.setMinimumSize(QtCore.QSize(201, 31))
        selectImage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        selectImage.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=selectImage)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 10, 1545, 844))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.full_screen_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.full_screen_layout.setContentsMargins(0, 0, 0, 0)
        self.full_screen_layout.setObjectName("full_screen_layout")
        self.side_bar_layout = QtWidgets.QVBoxLayout()
        self.side_bar_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.side_bar_layout.setSpacing(0)
        self.side_bar_layout.setObjectName("side_bar_layout")
        self.sidebar = QtWidgets.QWidget(parent=self.horizontalLayoutWidget)
        self.sidebar.setMinimumSize(QtCore.QSize(341, 601))
        self.sidebar.setMaximumSize(QtCore.QSize(241, 601))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.imageSelectionSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.imageSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.imageSelectionSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.imageSelectionSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.imageSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.imageSelectionSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.imageSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.imageSelectionSidebar.setObjectName("imageSelectionSidebar")
        self.imageSelectionLabelSidebar = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.imageSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.imageSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageSelectionLabelSidebar.setObjectName("imageSelectionLabelSidebar")
        self.imageLabel = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.imageLabel.setGeometry(QtCore.QRect(-60, 40, 191, 51))
        self.imageLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.phantomLabel = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.phantomLabel.setGeometry(QtCore.QRect(-50, 70, 191, 51))
        self.phantomLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold\n"
"}")
        self.phantomLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.phantomLabel.setObjectName("phantomLabel")
        self.roiSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.roiSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.roiSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.roiSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.roiSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.roiSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.roiSidebar.setObjectName("roiSidebar")
        self.roiSidebarLabel = QtWidgets.QLabel(parent=self.roiSidebar)
        self.roiSidebarLabel.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.roiSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.roiSidebarLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.roiSidebarLabel.setObjectName("roiSidebarLabel")
        self.rfAnalysisSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.rfAnalysisSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.rfAnalysisSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.rfAnalysisSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.rfAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.rfAnalysisSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rfAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rfAnalysisSidebar.setObjectName("rfAnalysisSidebar")
        self.rfAnalysisLabel = QtWidgets.QLabel(parent=self.rfAnalysisSidebar)
        self.rfAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.rfAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.rfAnalysisLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rfAnalysisLabel.setObjectName("rfAnalysisLabel")
        self.exportResultsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.exportResultsSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.exportResultsSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.exportResultsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.exportResultsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.exportResultsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.exportResultsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.exportResultsSidebar.setObjectName("exportResultsSidebar")
        self.exportResultsLabel = QtWidgets.QLabel(parent=self.exportResultsSidebar)
        self.exportResultsLabel.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.exportResultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.exportResultsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exportResultsLabel.setObjectName("exportResultsLabel")
        self.analysisParamsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.analysisParamsSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisParamsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.analysisParamsSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisParamsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.analysisParamsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.analysisParamsSidebar.setObjectName("analysisParamsSidebar")
        self.analysisParamsLabel = QtWidgets.QLabel(parent=self.analysisParamsSidebar)
        self.analysisParamsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisParamsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisParamsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.analysisParamsLabel.setObjectName("analysisParamsLabel")
        self.side_bar_layout.addWidget(self.sidebar)
        self.gridFrame = QtWidgets.QFrame(parent=self.horizontalLayoutWidget)
        self.gridFrame.setMinimumSize(QtCore.QSize(341, 0))
        self.gridFrame.setMaximumSize(QtCore.QSize(341, 16777215))
        self.gridFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.gridFrame.setObjectName("gridFrame")
        self.backButtonGrid = QtWidgets.QGridLayout(self.gridFrame)
        self.backButtonGrid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.backButtonGrid.setContentsMargins(10, 10, 10, 10)
        self.backButtonGrid.setObjectName("backButtonGrid")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.backButtonGrid.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.backButtonGrid.addItem(spacerItem1, 1, 1, 1, 1)
        self.back_button = QtWidgets.QPushButton(parent=self.gridFrame)
        self.back_button.setMinimumSize(QtCore.QSize(131, 41))
        self.back_button.setMaximumSize(QtCore.QSize(131, 41))
        self.back_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.backButtonGrid.addWidget(self.back_button, 1, 0, 1, 1)
        self.side_bar_layout.addWidget(self.gridFrame)
        self.full_screen_layout.addLayout(self.side_bar_layout)
        self.img_selection_layout = QtWidgets.QVBoxLayout()
        self.img_selection_layout.setContentsMargins(30, 30, 30, 30)
        self.img_selection_layout.setSpacing(20)
        self.img_selection_layout.setObjectName("img_selection_layout")
        self.select_data_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.select_data_label.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.select_data_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.select_data_label.setScaledContents(False)
        self.select_data_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.select_data_label.setWordWrap(True)
        self.select_data_label.setObjectName("select_data_label")
        self.img_selection_layout.addWidget(self.select_data_label)
        self.chooseImgPhantLayout = QtWidgets.QHBoxLayout()
        self.chooseImgPhantLayout.setObjectName("chooseImgPhantLayout")
        self.chooseImgLayout = QtWidgets.QVBoxLayout()
        self.chooseImgLayout.setContentsMargins(20, -1, 20, -1)
        self.chooseImgLayout.setObjectName("chooseImgLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.chooseImgLayout.addItem(spacerItem2)
        self.image_path_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.image_path_label.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.image_path_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.image_path_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.image_path_label.setObjectName("image_path_label")
        self.chooseImgLayout.addWidget(self.image_path_label)
        self.image_path_input = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.image_path_input.setMinimumSize(QtCore.QSize(201, 31))
        self.image_path_input.setMaximumSize(QtCore.QSize(401, 31))
        self.image_path_input.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.image_path_input.setObjectName("image_path_input")
        self.chooseImgLayout.addWidget(self.image_path_input, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.chooseImageButtonsLayout = QtWidgets.QHBoxLayout()
        self.chooseImageButtonsLayout.setObjectName("chooseImageButtonsLayout")
        self.choose_image_path_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.choose_image_path_button.setMinimumSize(QtCore.QSize(131, 41))
        self.choose_image_path_button.setMaximumSize(QtCore.QSize(131, 41))
        self.choose_image_path_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.choose_image_path_button.setObjectName("choose_image_path_button")
        self.chooseImageButtonsLayout.addWidget(self.choose_image_path_button)
        self.clear_image_path_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.clear_image_path_button.setMinimumSize(QtCore.QSize(131, 41))
        self.clear_image_path_button.setMaximumSize(QtCore.QSize(131, 41))
        self.clear_image_path_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clear_image_path_button.setObjectName("clear_image_path_button")
        self.chooseImageButtonsLayout.addWidget(self.clear_image_path_button)
        self.chooseImgLayout.addLayout(self.chooseImageButtonsLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.chooseImgLayout.addItem(spacerItem3)
        self.chooseImgPhantLayout.addLayout(self.chooseImgLayout)
        self.choosePhantomLayout = QtWidgets.QVBoxLayout()
        self.choosePhantomLayout.setContentsMargins(20, -1, 20, -1)
        self.choosePhantomLayout.setObjectName("choosePhantomLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.choosePhantomLayout.addItem(spacerItem4)
        self.phantom_path_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.phantom_path_label.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.phantom_path_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.phantom_path_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.phantom_path_label.setObjectName("phantom_path_label")
        self.choosePhantomLayout.addWidget(self.phantom_path_label)
        self.phantom_path_input = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.phantom_path_input.setMinimumSize(QtCore.QSize(201, 31))
        self.phantom_path_input.setMaximumSize(QtCore.QSize(401, 31))
        self.phantom_path_input.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.phantom_path_input.setObjectName("phantom_path_input")
        self.choosePhantomLayout.addWidget(self.phantom_path_input, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.choosePhantomButtonsLayout = QtWidgets.QHBoxLayout()
        self.choosePhantomButtonsLayout.setObjectName("choosePhantomButtonsLayout")
        self.choose_phantom_path_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.choose_phantom_path_button.setMinimumSize(QtCore.QSize(131, 41))
        self.choose_phantom_path_button.setMaximumSize(QtCore.QSize(131, 41))
        self.choose_phantom_path_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.choose_phantom_path_button.setObjectName("choose_phantom_path_button")
        self.choosePhantomButtonsLayout.addWidget(self.choose_phantom_path_button)
        self.clear_phantom_path_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.clear_phantom_path_button.setMinimumSize(QtCore.QSize(131, 41))
        self.clear_phantom_path_button.setMaximumSize(QtCore.QSize(131, 41))
        self.clear_phantom_path_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clear_phantom_path_button.setObjectName("clear_phantom_path_button")
        self.choosePhantomButtonsLayout.addWidget(self.clear_phantom_path_button)
        self.choosePhantomLayout.addLayout(self.choosePhantomButtonsLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.choosePhantomLayout.addItem(spacerItem5)
        self.chooseImgPhantLayout.addLayout(self.choosePhantomLayout)
        self.img_selection_layout.addLayout(self.chooseImgPhantLayout)
        self.loading_options_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.loading_options_label.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.loading_options_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.loading_options_label.setScaledContents(False)
        self.loading_options_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loading_options_label.setWordWrap(True)
        self.loading_options_label.setObjectName("loading_options_label")
        self.img_selection_layout.addWidget(self.loading_options_label)
        self.loading_options_table = QtWidgets.QTableWidget(parent=self.horizontalLayoutWidget)
        self.loading_options_table.setStyleSheet("QTableWidget {\n"
"    background: rgb(108, 108, 108);\n"
"    color: white;\n"
"}")
        self.loading_options_table.setDragEnabled(False)
        self.loading_options_table.setRowCount(0)
        self.loading_options_table.setColumnCount(0)
        self.loading_options_table.setObjectName("loading_options_table")
        self.loading_options_table.horizontalHeader().setCascadingSectionResizes(False)
        self.img_selection_layout.addWidget(self.loading_options_table)
        self.generate_image_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.generate_image_button.setMinimumSize(QtCore.QSize(131, 41))
        self.generate_image_button.setMaximumSize(QtCore.QSize(131, 41))
        self.generate_image_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.generate_image_button.setObjectName("generate_image_button")
        self.img_selection_layout.addWidget(self.generate_image_button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.loading_screen_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.loading_screen_label.setStyleSheet("QLabel {\n"
"    color: rgb(0, 255, 0);\n"
"    font-size: 20px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.loading_screen_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loading_screen_label.setObjectName("loading_screen_label")
        self.img_selection_layout.addWidget(self.loading_screen_label)
        self.select_image_error_msg = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.select_image_error_msg.setStyleSheet("QLabel {\n"
"    color: rgb(255, 0, 23);\n"
"    font-size: 20px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.select_image_error_msg.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.select_image_error_msg.setObjectName("select_image_error_msg")
        self.img_selection_layout.addWidget(self.select_image_error_msg)
        self.img_selection_layout.setStretch(0, 2)
        self.img_selection_layout.setStretch(1, 2)
        self.img_selection_layout.setStretch(4, 3)
        self.img_selection_layout.setStretch(6, 2)
        self.full_screen_layout.addLayout(self.img_selection_layout)
        self.full_screen_layout.setStretch(0, 1)
        self.full_screen_layout.setStretch(1, 5)

        self.retranslateUi(selectImage)
        QtCore.QMetaObject.connectSlotsByName(selectImage)

    def retranslateUi(self, selectImage):
        _translate = QtCore.QCoreApplication.translate
        selectImage.setWindowTitle(_translate("selectImage", "Select Ultrasound Image"))
        self.sidebar.setToolTip(_translate("selectImage", "<html><head/><body><p><br/></p></body></html>"))
        self.imageSelectionLabelSidebar.setText(_translate("selectImage", "Image Selection:"))
        self.imageLabel.setText(_translate("selectImage", "Image:"))
        self.phantomLabel.setText(_translate("selectImage", "Phantom:"))
        self.roiSidebarLabel.setText(_translate("selectImage", "Segmentation Selection"))
        self.rfAnalysisLabel.setText(_translate("selectImage", "QUS Analysis"))
        self.exportResultsLabel.setText(_translate("selectImage", "Visualization / Export"))
        self.analysisParamsLabel.setText(_translate("selectImage", "Analysis Parameter Selection"))
        self.back_button.setText(_translate("selectImage", "Back"))
        self.select_data_label.setText(_translate("selectImage", "Select Data and Phantom Files to Generate Ultrasound Image:"))
        self.image_path_label.setText(_translate("selectImage", "Input Path to Image file\n"
" (.rf, .rfd, .mat, .bin)"))
        self.choose_image_path_button.setText(_translate("selectImage", "Choose File"))
        self.clear_image_path_button.setText(_translate("selectImage", "Clear Path"))
        self.phantom_path_label.setText(_translate("selectImage", "Input Path to Phantom file\n"
" (.rf, .rfd, .mat, .bin)"))
        self.choose_phantom_path_button.setText(_translate("selectImage", "Choose File"))
        self.clear_phantom_path_button.setText(_translate("selectImage", "Clear Path"))
        self.loading_options_label.setText(_translate("selectImage", "\n"
"Image Loading Options:"))
        self.loading_options_table.setSortingEnabled(False)
        self.generate_image_button.setText(_translate("selectImage", "Generate Image"))
        self.loading_screen_label.setText(_translate("selectImage", "LOADING...."))
        self.select_image_error_msg.setText(_translate("selectImage", "ERROR: At least one dimension of phantom data\n"
"smaller than corresponding dimension\n"
"of image data"))
