# Form implementation generated from reading ui file 'D:\Omid\0_main\05.01.2026\5_QuantUS-OpenSource\QuantUS\src\qus\export_loading\ui\export_loading.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_exportLoading(object):
    def setupUi(self, exportLoading):
        exportLoading.setObjectName("exportLoading")
        exportLoading.resize(1400, 713)
        exportLoading.setMinimumSize(QtCore.QSize(1400, 662))
        exportLoading.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.main_layout = QtWidgets.QVBoxLayout(exportLoading)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.full_screen_layout = QtWidgets.QHBoxLayout()
        self.full_screen_layout.setContentsMargins(0, 0, 0, 0)
        self.full_screen_layout.setObjectName("full_screen_layout")
        self.side_bar_layout = QtWidgets.QVBoxLayout()
        self.side_bar_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.side_bar_layout.setSpacing(0)
        self.side_bar_layout.setObjectName("side_bar_layout")
        self.sidebar = QtWidgets.QWidget(parent=exportLoading)
        self.sidebar.setMinimumSize(QtCore.QSize(341, 601))
        self.sidebar.setMaximumSize(QtCore.QSize(241, 601))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.imageSelectionSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.imageSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.imageSelectionSidebar.setMinimumSize(QtCore.QSize(341, 121))
        self.imageSelectionSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.imageSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.imageSelectionSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.imageSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.imageSelectionSidebar.setObjectName("imageSelectionSidebar")
        self.imageSelectionLabelSidebar = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.imageSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.imageSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageSelectionLabelSidebar.setObjectName("imageSelectionLabelSidebar")
        self.imageLabel = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.imageLabel.setGeometry(QtCore.QRect(-60, 40, 191, 51))
        self.imageLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.phantomLabel = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.phantomLabel.setGeometry(QtCore.QRect(-50, 70, 191, 51))
        self.phantomLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold\n"
"}")
        self.phantomLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.phantomLabel.setObjectName("phantomLabel")
        self.image_path_input = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.image_path_input.setGeometry(QtCore.QRect(100, 40, 241, 51))
        self.image_path_input.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.image_path_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.image_path_input.setObjectName("image_path_input")
        self.phantom_path_input = QtWidgets.QLabel(parent=self.imageSelectionSidebar)
        self.phantom_path_input.setGeometry(QtCore.QRect(100, 70, 241, 51))
        self.phantom_path_input.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.phantom_path_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.phantom_path_input.setObjectName("phantom_path_input")
        self.segmentationSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.segmentationSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.segmentationSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.segmentationSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.segmentationSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.segmentationSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.segmentationSidebar.setObjectName("segmentationSidebar")
        self.segmentationSidebarLabel = QtWidgets.QLabel(parent=self.segmentationSidebar)
        self.segmentationSidebarLabel.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.segmentationSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.segmentationSidebarLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.segmentationSidebarLabel.setObjectName("segmentationSidebarLabel")
        self.analysisParamsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.analysisParamsSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisParamsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.analysisParamsSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisParamsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.analysisParamsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.analysisParamsSidebar.setObjectName("analysisParamsSidebar")
        self.analysisParamsLabel = QtWidgets.QLabel(parent=self.analysisParamsSidebar)
        self.analysisParamsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisParamsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisParamsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.analysisParamsLabel.setObjectName("analysisParamsLabel")
        self.rfAnalysisSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.rfAnalysisSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.rfAnalysisSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.rfAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.rfAnalysisSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rfAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rfAnalysisSidebar.setObjectName("rfAnalysisSidebar")
        self.rfAnalysisLabel = QtWidgets.QLabel(parent=self.rfAnalysisSidebar)
        self.rfAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.rfAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.rfAnalysisLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rfAnalysisLabel.setObjectName("rfAnalysisLabel")
        self.exportResultsSidebar = QtWidgets.QFrame(parent=self.sidebar)
        self.exportResultsSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.exportResultsSidebar.setMaximumSize(QtCore.QSize(341, 121))
        self.exportResultsSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.exportResultsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.exportResultsSidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.exportResultsSidebar.setObjectName("exportResultsSidebar")
        self.exportResultsLabel = QtWidgets.QLabel(parent=self.exportResultsSidebar)
        self.exportResultsLabel.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.exportResultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.exportResultsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exportResultsLabel.setObjectName("exportResultsLabel")
        self.side_bar_layout.addWidget(self.sidebar)
        self.gridFrame = QtWidgets.QFrame(parent=exportLoading)
        self.gridFrame.setMaximumSize(QtCore.QSize(341, 16777215))
        self.gridFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.gridFrame.setObjectName("gridFrame")
        self.backButtonGrid = QtWidgets.QGridLayout(self.gridFrame)
        self.backButtonGrid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.backButtonGrid.setContentsMargins(10, 10, 10, 10)
        self.backButtonGrid.setObjectName("backButtonGrid")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.backButtonGrid.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.backButtonGrid.addItem(spacerItem1, 1, 1, 1, 1)
        self.back_button = QtWidgets.QPushButton(parent=self.gridFrame)
        self.back_button.setMinimumSize(QtCore.QSize(200, 41))
        self.back_button.setMaximumSize(QtCore.QSize(200, 41))
        self.back_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.backButtonGrid.addWidget(self.back_button, 1, 0, 1, 1)
        self.side_bar_layout.addWidget(self.gridFrame)
        self.full_screen_layout.addLayout(self.side_bar_layout)
        self.export_loading_layout = QtWidgets.QVBoxLayout()
        self.export_loading_layout.setContentsMargins(20, 20, 20, 20)
        self.export_loading_layout.setSpacing(10)
        self.export_loading_layout.setObjectName("export_loading_layout")
        self.title_label = QtWidgets.QLabel(parent=exportLoading)
        self.title_label.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.title_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.title_label.setScaledContents(False)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setWordWrap(False)
        self.title_label.setObjectName("title_label")
        self.export_loading_layout.addWidget(self.title_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.export_stack = QtWidgets.QStackedWidget(parent=exportLoading)
        self.export_stack.setStyleSheet("QStackedWidget {\n"
"    background-color: transparent;\n"
"}")
        self.export_stack.setObjectName("export_stack")
        self.export_loading_layout.addWidget(self.export_stack)
        self.execute_button = QtWidgets.QPushButton(parent=exportLoading)
        self.execute_button.setMinimumSize(QtCore.QSize(250, 41))
        self.execute_button.setMaximumSize(QtCore.QSize(250, 41))
        self.execute_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(0, 150, 0);\n"
"    border-radius: 15px;\n"
"}")
        self.execute_button.setObjectName("execute_button")
        self.export_loading_layout.addWidget(self.execute_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.export_loading_layout.addItem(spacerItem2)
        self.export_loading_layout.setStretch(0, 1)
        self.export_loading_layout.setStretch(1, 10)
        self.export_loading_layout.setStretch(3, 1)
        self.full_screen_layout.addLayout(self.export_loading_layout)
        self.main_layout.addLayout(self.full_screen_layout)

        self.retranslateUi(exportLoading)
        QtCore.QMetaObject.connectSlotsByName(exportLoading)

    def retranslateUi(self, exportLoading):
        _translate = QtCore.QCoreApplication.translate
        exportLoading.setWindowTitle(_translate("exportLoading", "Data Export"))
        self.sidebar.setToolTip(_translate("exportLoading", "<html><head/><body><p><br/></p></body></html>"))
        self.imageSelectionLabelSidebar.setText(_translate("exportLoading", "Image Selection:"))
        self.imageLabel.setText(_translate("exportLoading", "Image:"))
        self.phantomLabel.setText(_translate("exportLoading", "Phantom:"))
        self.image_path_input.setText(_translate("exportLoading", "Sample filename "))
        self.phantom_path_input.setText(_translate("exportLoading", "Sample filename "))
        self.segmentationSidebarLabel.setText(_translate("exportLoading", "Segmentation Selection"))
        self.analysisParamsLabel.setText(_translate("exportLoading", "Analysis Parameter Selection"))
        self.rfAnalysisLabel.setText(_translate("exportLoading", "QUS Analysis"))
        self.exportResultsLabel.setText(_translate("exportLoading", "Visualization / Export"))
        self.back_button.setText(_translate("exportLoading", "Back"))
        self.title_label.setText(_translate("exportLoading", "Data Export Configuration"))
        self.execute_button.setText(_translate("exportLoading", "Execute Export"))
